"""Appendix tables for the despace boundary analysis, whole-input version (context and every answer option
despaced together, the Despace axis of tab:main_robust).

Derived 2026-10-06 from lingua/apps/aunet/despace_patch_tables.py, which reports the context-only ladder and
splits context / answer / both; the paper appendix now keeps only the whole-input setting.

    python scripts/probes/despace/despace_patch_tables.py [<patch_stats.json> [<sweep.json> [<out_dir>]]]

Inputs: patch_stats.json of lingua/apps/aunet/despace_patch_stats.py (region "all" = BOS-free context+option),
        reports/despace_p_sweep/sweep.json (accuracy vs p, region "all"; p=1 equals the Despace column).
Writes despace_ladder.tex and despace_recall_quartiles.tex.
"""
import json
import os
import sys

ROOT = "/mnt/ssd2/hyun2/AUNet"
SRC = f"{ROOT}/runs/robustness_despace_bits/patch_stats_both4/patch_stats.json"
SWEEP = f"{ROOT}/reports/despace_p_sweep/sweep.json"
OUT = f"{ROOT}/paper_overleaf/table_appendix"
HEAD = "% GENERATED by AUNet/scripts/probes/despace/despace_patch_tables.py — edit the script, not this file.\n"
MODELS = [("aunet", "AUNet", "AUNet"), ("bpebyte", "BPEByte (ours)", "BPEByte")]   # key, label, sweep.json name
LADDER = [(0, "clean", "0.0"), (10, "all10", "0.1"), (40, "all40", "0.4"), (70, "all70", "0.7"),
          (100, "despaceall", "1.0")]


def f(x, p=2):
    return "--" if x is None else f"{x:.{p}f}"


def _signed(x, p=3):
    return "$0.000$" if round(x, p) == 0 else f"${x:+.{p}f}$"


def ladder(s, sw):
    rows = []
    for key, name, swn in MODELS:
        d = s["models"][key]
        acc = sw[swn]["all"]
        for i, (pct, v, sp) in enumerate(LADDER):
            t = d["table"][f"avg/{v}/all"]
            dacc = "--" if v == "clean" else f"${acc[sp] - acc['0.0']:+.1f}$"
            rows.append(" & ".join([name if i == 0 else "", f"{pct}\\%", f(t["patches_per_item"]),
                                    f(t["bytes_per_patch"]), f(t["byte_weighted_len"]), f(t["p90"], 0),
                                    f(t["max"], 0), f(100 * t["bytes_in_ge16"]), f(t["cut_recall"], 3),
                                    f(t["cut_precision"], 3), f(t["patch_jaccard"], 3), dacc]) + " \\\\")
        rows.append("\\midrule")
    rows[-1] = "\\bottomrule"
    return HEAD + r"""\begin{table*}[t]
\centering
\caption{\hyun{Patching under graded despacing: each intra-line space of the context and of every answer option is removed independently with probability $p$ (removals nest across $p$; $100\%$ is the \textit{Despace} setting of Table~\ref{tab:main_robust}), pooled over every (context, answer option) pair of HellaSwag, ARC-Easy, ARC-Challenge, and PIQA. Statistics cover the whole input (context followed by the option, BOS excluded). \emph{Patches} is the number of patches per input, \emph{Byte-wt.}\ the mean length of the patch containing a random byte ($\sum\ell^2/\sum\ell$), and \emph{$>$16\,B} the share of bytes in patches longer than $16$ bytes. \emph{Cut R}/\emph{Cut P} are the recall and precision of the clean parse's boundaries after projecting both parses onto the space-free byte sequence, which despacing leaves unchanged; \emph{Patch J} is the Jaccard overlap of the two patch sets. $\Delta$Acc is the accuracy change of Figure~\ref{fig:despace_sweep} (points).}}
\label{tab:despace_ladder}
\small
\setlength{\tabcolsep}{4.5pt}
\begin{tabular}{llrrrrrrrrrr}
\toprule
\textbf{Model} & \textbf{$p$} & \textbf{Patches} & \textbf{B/patch} & \textbf{Byte-wt.} & \textbf{P90} & \textbf{Max} & \textbf{$>$16\,B (\%)} & \textbf{Cut R} & \textbf{Cut P} & \textbf{Patch J} & \textbf{$\Delta$Acc} \\
\midrule
""" + "\n".join(rows) + r"""
\end{tabular}
\end{table*}
"""


def quartiles(s):
    # rows = quartiles (+ rho), columns = models: two models fit one column without shrinking
    R = [s["models"][key]["recall_vs_acc"]["paper"]["despaceall"] for key, _, _ in MODELS]
    rows = []
    for q in (1, 2, 3, 4):
        cells = []
        for r in R:
            b = {b["quartile"]: b for b in r["bins"]}.get(q)
            cells.append("--" if b is None else f"${100 * b['delta']:+.2f}$ {{\\scriptsize({b['mean_recall']:.2f})}}")
        rows.append(" & ".join([f"Q{q}", *cells]) + " \\\\")
    rows += ["\\midrule", " & ".join(["$\\rho$", *(_signed(r["spearman_recall_vs_flip"]) for r in R)]) + " \\\\"]
    return HEAD + r"""\begin{table}[t]
\centering
\caption{\hyun{Per-item boundary loss versus accuracy change under \textit{Despace} (all spaces removed from the context and every answer option). Items are split into quartiles of the cut recall of the whole input (Q1 = most clean boundaries lost; mean recall in parentheses), within each task and then pooled; entries are $\Delta$Acc in percentage points. $\rho$ is the Spearman correlation between an item's cut recall and its accuracy change, averaged over tasks.}}
\label{tab:despace_recall_quartiles}
\small
\setlength{\tabcolsep}{6pt}
\begin{tabular}{lcc}
\toprule
\textbf{Recall quartile} & \textbf{""" + r"} & \textbf{".join(n for _, n, _ in MODELS) + r"""} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""


def main():
    a = sys.argv[1:]
    src = a[0] if len(a) > 0 else SRC
    sweep = a[1] if len(a) > 1 else SWEEP
    out = a[2] if len(a) > 2 else OUT
    s, sw = json.load(open(src)), json.load(open(sweep))
    for name, text in (("despace_ladder", ladder(s, sw)), ("despace_recall_quartiles", quartiles(s))):
        path = os.path.join(out, f"{name}.tex")
        open(path, "w").write(text)
        print(path)


if __name__ == "__main__":
    main()
