#!/usr/bin/env python3
"""Write reports/longctx/EXAMPLES.md: one real prompt + gold answer set per experiment.

Long haystacks are elided around the part that matters (needle / gold pair / chain), with the
number of elided bytes shown, so every example stays readable while being an actual dataset row.
"""
import argparse
import json
from pathlib import Path


def load(p):
    return [json.loads(l) for l in open(p)]


def elide(text, keep, ctx=160):
    """Keep the head, `ctx` chars around every string in `keep`, and the tail."""
    spans = [(0, 220), (len(text) - 260, len(text))]
    for k in keep:
        i = text.find(k)
        if i >= 0:
            spans.append((max(0, i - ctx), min(len(text), i + len(k) + ctx)))
    spans.sort()
    merged = []
    for a, b in spans:
        if merged and a <= merged[-1][1] + 60:      # never elide a trivially short gap
            merged[-1] = (merged[-1][0], max(merged[-1][1], b))
        else:
            merged.append((a, b))
    out, prev = [], 0
    for a, b in merged:
        if a > prev:
            out.append(f"\n[… {len(text[prev:a].encode())} bytes elided …]\n")
        out.append(text[a:b])
        prev = b
    return "".join(out)


def block(r, keep, note):
    ans = r.get("answers") or [r["options"][r["gold"]].strip()]
    s = [f"- id `{r['id']}` · prompt {r['prompt_bytes']} B · {note}",
         f"- **gold answer set**: {ans}",
         "", "```text", elide(r["prompt"], keep), "```", ""]
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/longctx")
    ap.add_argument("--out", default="reports/longctx/EXAMPLES.md")
    a = ap.parse_args()
    nt, kv = load(f"{a.data}/needle_types.jsonl"), load(f"{a.data}/kv_litm.jsonl")
    ra, icl = load(f"{a.data}/ruler_agg.jsonl"), load(f"{a.data}/icl.jsonl")
    md = ["# Long-context suite — example prompts and answer sets", "",
          "Every block is a real row of `data/longctx/*.jsonl` (seed 0). The model continues the prompt "
          "with greedy decoding; the first `window` generated **bytes** are scored (same for every model). "
          "`[… N bytes elided …]` marks haystack cut for display only.", ""]

    md += ["## 1. Needle value-type sweep (`needle_types`, 1600 rows)", "",
           "Haystack = DCLM essay window of 1/2/4/6 KB; needle inserted at depth 0.1/0.3/0.5/0.7/0.9; "
           "10 value types × 4 lengths × 5 depths × 8. Score = gold value is a substring of the first "
           "`len(value)+24` generated bytes.", ""]
    r = next(x for x in nt if x["cond"] == "uuid" and x["length"] == 1024 and x["pos"] == 0.5)
    md += block(r, [r["answers"][0]], "type `uuid`, depth 0.5")
    md += ["Same template, one sampled value per type:", "", "| type | example gold value | bytes |", "|---|---|---|"]
    for vt in ["num7", "num20", "uuid", "hex32", "alnum12", "ident", "nonce", "word", "han4", "hangul4"]:
        v = next(x for x in nt if x["cond"] == vt)["answers"][0]
        md.append(f"| {vt} | `{v}` | {len(v.encode())} |")
    md += [""]

    md += ["## 2. Lost-in-the-Middle KV retrieval (`kv_litm`, 750 rows)", "",
           "JSON object of k ∈ {5,10,25,50,60} random UUID→UUID pairs; the queried key sits at relative "
           "position 0/0.25/0.5/0.75/1.0; 30 per cell. Score = gold value in the first 60 generated bytes.", ""]
    r = next(x for x in kv if x["length"] == 10 and x["pos"] == 0.5)
    md += block(r, [r["answers"][0]], "k=10, gold pair at position 0.5")

    md += ["## 3. RULER aggregation (`ruler_agg`, 698 rows)", "",
           "Each prompt starts with RULER's one-shot solved example, then the scored instance. "
           "Score = recall of the gold set inside the answer window.", ""]
    r = next(x for x in ra if x["task"] == "vt" and x["cond"] == "c1h4" and x["length"] == 1024)
    scored = r["prompt"].split("\n\n")
    md += ["### 3a. Variable Tracking — 1 chain × 4 hops (also 2 chains × 4 hops), 1/2/4/6 KB, 50 each", ""]
    md += block(r, [f"VAR {n} " for n in r["answers"]], "1 chain, 4 hops (5 names to list)")
    r = next(x for x in ra if x["task"] == "cwe" and x["length"] == 2048)
    md += ["### 3b. Common Words Extraction — top-10 words of a numbered list, 2/4/6 KB, 50 each", ""]
    md += block(r, [], "10 common words (freq ≥ 4) among words that appear 2×")
    r = next(x for x in ra if x["task"] == "fwe" and x["length"] == 2048)
    md += ["### 3c. Frequent Words Extraction — top-3 Zipf(α=2) coded words, 2/4/6 KB, 50 each", ""]
    md += block(r, [], "top-3 by frequency (ties at rank 3/4 excluded at build time)")

    md += ["## 4. Many-shot ICL (`icl`, 7800 rows)", "",
           "300 test items per dataset; k ∈ {1,2,4,…,64} class-balanced demos (the k-shot set is a prefix "
           "of the 2k-shot set) until the prompt would exceed 7.4 KB. SST-2 / TREC-coarse / AG News: "
           "score log P(\" label\" | prompt) for every label, correct iff argmax = gold. TREC-fine (50 "
           "labels): greedy generation, first non-empty line must equal the gold label.", ""]
    for ds, k in [("sst2", 2), ("trec_coarse", 4), ("agnews", 1), ("trec_fine", 4)]:
        r = next(x for x in icl if x["cond"] == ds and x["length"] == k)
        opts = r.get("options")
        note = f"{ds}, {k}-shot" + (f", options {[o.strip() for o in opts]}" if opts else ", 50 labels")
        md += [f"**{ds}**", ""] + block(r, [], note)
    Path(a.out).write_text("\n".join(md))
    print(f"wrote {a.out} ({len(md)} lines)")


if __name__ == "__main__":
    main()
