#!/usr/bin/env python3
"""Appendix material for BLT at the compression-matched entropy threshold (theta=1.61) vs released (1.335).

Writes into paper_overleaf (every number generated, none transcribed):
  table_appendix/blt_threshold_patch.tex       per-benchmark patch length (mean +- std, 1-byte share)
  table_appendix/blt_threshold_sniah.tex       S-NIAH exact recall per cell
  table_appendix/blt_threshold_downstream.tex  per-task 0/3/5-shot accuracy
  table_appendix/blt_threshold_robust.tex      per-task Noise/Typo/Despace dAcc
  figure_appendix/blt_threshold_boundaries.tex BLT rows of the parsing-boundary examples at both thresholds
  figure_appendix/patch_len_hist_t161.{tex,pdf} patch-length distributions with BLT at theta=1.61

Sources:
  reports/patch_stats/hist_blt.json, hist_blt_t16094.json      (measure_blt.py, 512-byte window)
  reports/ext_ci/blt_official/{,t1609_}{sniah,ds0,ds3,ds5,noise_*,typo_*,despace}.json (run_ext.py)
  reports/parse/boundary5_starts.json keys BLT-rel / BLT-t1609
  reports/blt_t1609/patch_len_hist.pdf                           (make_tables.py --blt_hist ... --out_dir)

  python scripts/probes/ext_ci/make_blt_threshold_appendix.py
"""
import glob, json, shutil, statistics as st
from pathlib import Path

L = Path("/mnt/ssd2/hyun2/AUNet")
OVL = L / "paper_overleaf"
BO = L / "reports/ext_ci/blt_official"
PS = L / "reports/patch_stats"
TH = (("", r"$\theta{=}1.34$"), ("t1609_", r"$\theta{=}1.61$"))
HIST = {"": "hist_blt.json", "t1609_": "hist_blt_t16094.json"}
TN = {"hellaswag": "HellaSwag", "arc_easy": "ARC-Easy", "arc_challenge": "ARC-Challenge", "piqa": "PIQA",
      "winogrande": "WinoGrande", "boolq": "BoolQ", "mmlu_text": "MMLU"}
MET = {"hellaswag": "acc_norm", "arc_easy": "acc_norm", "arc_challenge": "acc_norm", "piqa": "acc_norm",
       "winogrande": "acc", "boolq": "acc", "mmlu_text": "acc"}
R5 = ("hellaswag", "arc_easy", "arc_challenge", "piqa", "boolq")
GEN = "% GENERATED by AUNet/scripts/probes/ext_ci/make_blt_threshold_appendix.py — edit the script, not this file."


def load(prefix, name):
    p = BO / f"{prefix}{name}.json"
    if p.exists():
        return json.load(open(p))
    out = {"results": {}}
    for q in sorted(glob.glob(str(BO / f"{prefix}{name}_*.json"))):
        out["results"].update(json.load(open(q))["results"])
    return out


# ---------------------------------------------------------------- patch lengths
PATCH_ROWS = [("DCLM windows", ["dclm/dclm"])] + \
    [(TN[t], [f"downstream/{t}"]) for t in ("hellaswag", "arc_easy", "arc_challenge", "piqa", "winogrande", "boolq", "mmlu_text")] + \
    [(f"S-NIAH-{i}", [f"sniah/sniah{i}"]) for i in (1, 2, 3)] + \
    [("Clean (5-task suite)", [f"downstream/{t}" for t in R5]), ("Noise", [f"noise/{t}" for t in R5]),
     ("Typo", [f"typo/{t}" for t in R5]), ("Despace", [f"despace/{t}" for t in R5])]


def patch_stats(bench, keys):
    c = {}
    for k in keys:
        for Ls, n in bench[k]["hist"].items():
            c[int(Ls)] = c.get(int(Ls), 0) + n
    N = sum(c.values()); B = sum(L * n for L, n in c.items())
    mean = B / N
    sd = (sum(n * (L - mean) ** 2 for L, n in c.items()) / N) ** 0.5
    return mean, sd, c.get(1, 0) / N


def table_patch():
    H = {p: json.load(open(PS / f)) ["benches"] for p, f in HIST.items()}
    out = [GEN, r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}", r"\fitcolumn{%",
           r"\begin{tabular}{lcccc}", r"\toprule",
           r" & \multicolumn{2}{c}{" + TH[0][1] + r"} & \multicolumn{2}{c}{" + TH[1][1] + r"} \\",
           r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
           r"\textbf{Inputs} & B/patch & 1-byte (\%) & B/patch & 1-byte (\%) \\", r"\midrule"]
    for i, (label, keys) in enumerate(PATCH_ROWS):
        if label in ("HellaSwag", "S-NIAH-1", "Clean (5-task suite)"):
            out.append(r"\midrule")
        cells = []
        for p, _ in TH:
            m, sd, one = patch_stats(H[p], keys)
            cells += [f"{m:.2f}\\,{{\\scriptsize$\\pm${sd:.2f}}}", f"{100 * one:.1f}"]
        out.append(f"{label} & " + " & ".join(cells) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}", "}",
            r"\caption{\hyun{BLT patch length at the released entropy threshold ($\theta{=}1.34$) and at the "
            r"compression-matched threshold ($\theta{=}1.61$), on the inputs of Table~\ref{tab:patch_stats} "
            r"(mean $\pm$ standard deviation in bytes; \emph{1-byte}: share of single-byte patches). Both use the "
            r"entropy model's $512$-byte sliding window. On the clean inputs of the five downstream tasks behind the "
            r"main-table average, $\theta{=}1.61$ gives $4.65$ bytes per patch, matching the three matched models.}}",
            r"\label{tab:blt_threshold_patch}", r"\end{table}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- S-NIAH
def table_sniah():
    S = {p: load(p, "sniah") for p, _ in TH}
    lens = (512, 1024, 2048, 4096)
    out = [GEN, r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4.5pt}", r"\fitcolumn{%",
           r"\begin{tabular}{llccccc}", r"\toprule",
           r"\textbf{Task} & \textbf{BLT} & \textbf{0.5k} & \textbf{1k} & \textbf{2k} & \textbf{4k} & \textbf{Mean} \\",
           r"\midrule"]
    for ti in (1, 2, 3):
        if ti > 1:
            out.append(r"\midrule")
        for j, (p, lab) in enumerate(TH):
            cells = [S[p]["per_cell"][f"sniah{ti}/{L}"] for L in lens]
            first = f"S-NIAH-{ti}" if j == 0 else ""
            out.append(f"{first} & {lab} & " + " & ".join(f"{v:.2f}" for v in cells)
                       + f" & {S[p]['per_task'][f'sniah{ti}']:.3f} \\\\")
    out.append(r"\midrule")
    for p, lab in TH:
        out.append(f"Overall & {lab} & & & & & {S[p]['mean']:.3f} \\\\")
    out += [r"\bottomrule", r"\end{tabular}", "}",
            r"\caption{\hyun{BLT single-key exact recall (S-NIAH) by context length (bytes) at both entropy "
            r"thresholds, $n{=}250$ per cell, on the prompts of Table~\ref{tab:sniah_full}.}}",
            r"\label{tab:blt_threshold_sniah}", r"\end{table}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- downstream
def table_downstream():
    D = {(p, k): load(p, f"ds{k}")["results"] for p, _ in TH for k in (0, 3, 5)}

    def acc(p, k, t):
        r = D[(p, k)].get(t)
        return None if r is None else 100 * r[f"{MET[t]},none"]
    tasks = ("hellaswag", "arc_easy", "arc_challenge", "piqa", "winogrande", "boolq", "mmlu_text")
    out = [GEN, r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{3.5pt}", r"\fitcolumn{%",
           r"\begin{tabular}{lcccccc}", r"\toprule",
           r" & \multicolumn{2}{c}{0-shot} & \multicolumn{2}{c}{3-shot} & \multicolumn{2}{c}{5-shot} \\",
           r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
           r"\textbf{Task} & 1.34 & 1.61 & 1.34 & 1.61 & 1.34 & 1.61 \\", r"\midrule"]
    for t in tasks:
        cells = []
        for k in (0, 3, 5):
            for p, _ in TH:
                v = acc(p, k, t)
                cells.append("--" if v is None else f"{v:.1f}")
        out.append(f"{TN[t]} & " + " & ".join(cells) + r" \\")
    out.append(r"\midrule")
    cells = []
    for k in (0, 3, 5):
        for p, _ in TH:
            cells.append(f"{st.mean(acc(p, k, t) for t in tasks[:5]):.1f}")
    out.append(r"Avg (5-task) & " + " & ".join(cells) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}", "}",
            r"\caption{\hyun{BLT per-task downstream accuracy at the released ($1.34$) and compression-matched "
            r"($1.61$) entropy thresholds (same convention and context limits as "
            r"Tables~\ref{tab:downstream_0shot}--\ref{tab:downstream_5shot}; ``--'': prompt exceeds BLT's "
            r"$4096$-byte context). The five-task averages are the BLT rows of Table~\ref{tab:main_13b}.}}",
            r"\label{tab:blt_threshold_downstream}", r"\end{table}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- robustness
def axis_cell(res, t, ax):
    m = "acc" if t == "boolq" else "acc_norm"
    if ax == "despace":
        c, q = res.get(f"despace_mc_{t}_clean"), res.get(f"despace_mc_{t}_despaceall")
        return None if not (c and q) else 100 * (q["acc"] - c["acc"])
    vs = [v for k, v in res.items() if k.startswith(f"{t}_{ax}_") and not k.endswith("_avg") and isinstance(v, dict)
          and f"{m},none" in v]
    c = res.get(t)
    if not vs or not c:
        return None
    return 100 * (st.mean(v[f"{m},none"] for v in vs) - c[f"{m},none"])


def table_robust():
    R = {(p, ax): load(p, ax)["results"] for p, _ in TH for ax in ("noise", "typo", "despace")}
    out = [GEN, r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{3.5pt}", r"\fitcolumn{%",
           r"\begin{tabular}{lcccccc}", r"\toprule",
           r" & \multicolumn{2}{c}{\textit{Noise}} & \multicolumn{2}{c}{\textit{Typo}} & \multicolumn{2}{c}{\textit{Despace}} \\",
           r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
           r"\textbf{Task} & 1.34 & 1.61 & 1.34 & 1.61 & 1.34 & 1.61 \\", r"\midrule"]
    means = {}
    for t in R5:
        cells = []
        for ax in ("noise", "typo", "despace"):
            for p, _ in TH:
                v = axis_cell(R[(p, ax)], t, ax)
                means.setdefault((p, ax), []).append(v)
                cells.append(f"${v:+.1f}$")
        out.append(f"{TN[t]} & " + " & ".join(cells) + r" \\")
    out.append(r"\midrule")
    out.append(r"Average & " + " & ".join(f"${st.mean(means[(p, ax)]):+.1f}$"
                                          for ax in ("noise", "typo", "despace") for p, _ in TH) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}", "}",
            r"\caption{\hyun{BLT accuracy change ($\Delta$Acc, points) under the perturbations of "
            r"Table~\ref{tab:robustness_detail} at the released ($1.34$) and compression-matched ($1.61$) entropy "
            r"thresholds. The absolute averages are the BLT robustness entries of Table~\ref{tab:main_13b}.}}",
            r"\label{tab:blt_threshold_robust}", r"\end{table}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- boundary examples
def esc(ch):
    return {" ": r"\textvisiblespace{}", "{": r"\{", "}": r"\}", "\\": r"\textbackslash{}", "_": r"\_", "%": r"\%",
            "$": r"\$", "&": r"\&", "#": r"\#", "^": r"\^{}", "~": r"\~{}"}.get(ch, ch)


def render(text, starts):
    s = set(starts)
    return r"\allowbreak{}".join((f"\\bb{{{esc(c)}}}" if i in s else esc(c)) for i, c in enumerate(text))


def figure_boundaries():
    D = json.load(open(L / "reports/parse/boundary5_starts.json"))
    out = [GEN, r"\begin{figure}[t]"]
    for key, title in (("hellaswag", "HellaSwag"), ("arc_easy", "ARC-Easy")):
        t = D[key]["text"]; n = len(t.encode())
        out += [r"\begin{quote}\footnotesize\ttfamily\raggedright\setlength{\emergencystretch}{3em}",
                r"{\centering\textit{" + title + r"}\par}"]
        for k, lab in (("BLT-rel", r"$\theta{=}1.34$"), ("BLT-t1609", r"$\theta{=}1.61$")):
            s = D[key][k]
            out += [f"\\textbf{{BLT}} {lab} ({len(s)} patches, {n / len(s):.1f}~B/patch):\\\\[1pt]", render(t, s) + r"\\[3pt]"]
        out.append(r"\end{quote}")
    out += [r"\caption{\hyun{BLT patch starts (\bb{pink}) on the two items of the parsing-boundary examples "
            r"(Appendix~\ref{app:boundary_examples}) at the released and compression-matched entropy thresholds. "
            r"Raising the threshold removes boundaries only where the entropy lies between the two thresholds; "
            r"every $\theta{=}1.61$ boundary is also a $\theta{=}1.34$ boundary.}}",
            r"\label{fig:blt_threshold_boundaries}", r"\end{figure}", ""]
    return "\n".join(out)


def figure_hist():
    shutil.copy(L / "reports/blt_t1609/patch_len_hist.pdf", OVL / "figure_appendix/patch_len_hist_t161.pdf")
    return "\n".join([GEN, r"\begin{figure*}[t]", r"\centering",
                      r"\includegraphics[width=0.95\textwidth]{figure_appendix/patch_len_hist_t161.pdf}",
                      r"\caption{\hyun{Patch-length distributions as in Figure~\ref{fig:patch_len_hist}, with BLT at "
                      r"the compression-matched entropy threshold ($\theta{=}1.61$).}}",
                      r"\label{fig:patch_len_hist_t161}", r"\end{figure*}", ""])


def main():
    D = json.load(open(L / "reports/parse/boundary5_starts.json"))
    for k in D:   # sanity: higher threshold can only remove boundaries
        assert set(D[k]["BLT-t1609"]) <= set(D[k]["BLT-rel"]), k
    files = {"table_appendix/blt_threshold_patch.tex": table_patch(),
             "table_appendix/blt_threshold_sniah.tex": table_sniah(),
             "table_appendix/blt_threshold_downstream.tex": table_downstream(),
             "table_appendix/blt_threshold_robust.tex": table_robust(),
             "figure_appendix/blt_threshold_boundaries.tex": figure_boundaries(),
             "figure_appendix/patch_len_hist_t161.tex": figure_hist()}
    for f, s in files.items():
        (OVL / f).write_text(s)
        print("wrote", f)


if __name__ == "__main__":
    main()
