"""Appendix table tab:boolq_robust from runs/robustness_boolq_ctx/boolq_ctx_ci.json (boolq_ctx_ci.py): BoolQ clean
accuracy and the change under each perturbation applied to the context only (passage + question; the yes/no labels are
untouched), +- = half-width of the paired item-bootstrap 95% CI. Not part of the main-table averages.
  python make_boolq_table.py --out paper_overleaf/table_appendix/boolq_robust.tex"""
import argparse, json

J = "/mnt/ssd2/hyun2/AUNet/runs/robustness_boolq_ctx/boolq_ctx_ci.json"
COLS = [("llama", r"\textbf{Transformer}"), ("aunet", r"\textbf{AUNet}"), ("bpebyte", r"\textbf{BPEByte}"),
        ("blt", r"\textbf{BLT}$^{\dagger}$"), ("blt1609", r"\textbf{BLT}$^{\dagger}$ ($\theta{=}1.61$)"),
        ("hnet", r"\textbf{H-Net}$^{\ddagger}$")]
ROWS = [("pbp", r"\textit{PBP}"), ("noise", r"\textit{Noise}"), ("typo", r"\textit{Typo}"),
        ("despace", r"\textit{Despace}"), ("leet", r"\textit{Leet}")]


def sgn(x):
    return f"${'+' if x >= 0 else '-'}${abs(x):.2f}" if abs(x) >= 0.005 else "0.00"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    R = json.load(open(J))
    o = ["% GENERATED by AUNet scripts/probes/boolq_both/make_boolq_table.py (branch boolq-both) from",
         "% runs/robustness_boolq_ctx/boolq_ctx_ci.json -- edit the script, not this file.",
         r"\begin{table*}[t]", r"\centering",
         r"\caption{\hyun{BoolQ robustness at 1B with every perturbation applied to the \emph{context only} (passage and "
         r"question); the answer labels ``yes''/``no'' are left unchanged (Appendix~\ref{app:boolq_robust}). First $2{,}000$ "
         r"validation items, the perturbation seed of Table~\ref{tab:main_robust}, \texttt{acc}. Each cell gives the change "
         r"$\Delta$ from the model's clean accuracy in points, with the half-width of the paired item-bootstrap $95\%$ "
         r"confidence interval ($2{,}000$ resamples; \textit{PBP} is a point estimate, as in Table~\ref{tab:main_robust}). "
         r"These results are not part of the averages of Table~\ref{tab:main_robust}. $^{\dagger}$BLT and $^{\ddagger}$H-Net "
         r"are external references.}}",
         r"\label{tab:boolq_robust}", r"\small", r"\setlength{\tabcolsep}{3pt}", r"\fitcolumn[\textwidth]{%",
         r"\begin{tabular}{lcccccc}", r"\toprule",
         " & " + " & ".join(c for _, c in COLS) + r" \\", r"\midrule",
         r"Clean accuracy & " + " & ".join(f"{R[m]['noise']['clean']:.2f}" for m, _ in COLS) + r" \\", r"\midrule"]
    for ax, name in ROWS:
        cells = []
        for m, _ in COLS:
            r = R[m][ax]
            cells.append(sgn(r["delta"]) + (rf"\ci{{{(r['hi'] - r['lo']) / 2:.1f}}}" if "lo" in r else ""))
        o.append(f"{name} & " + " & ".join(cells) + r" \\")
    o += [r"\bottomrule", r"\end{tabular}", "}", r"\end{table*}", ""]
    open(a.out, "w").write("\n".join(o))
    print(a.out)


if __name__ == "__main__":
    main()
