#!/usr/bin/env python3
"""Accuracy by the gold option's position in the listing, for the five main models.

echo_all lists the options in their original order ("Options: (A) .. (B) .." before the question), so the
gold index is its listed position. clean (no listing) on the same items is the control: there the
"position" is only the option's index, which the model never sees as a position.
4-option items (ARC-E / ARC-C / HellaSwag with 4 choices) are pooled; PIQA (2 options) is reported separately.

  python scripts/probes/blt_weak/position_table.py --root reports/blt_weak > reports/blt_weak/POSITION.md
"""
import argparse
import glob
import json
import math
from collections import defaultdict

MODELS = [("subword_llama", "Llama"), ("aunet_static", "AU-Net"), ("byte_greedyroot", "BPEByte"),
          ("hnet_1stage_XL", "H-Net"), ("blt_1b", "BLT-1B")]
L = "ABCD"


def cell(v):
    if not v:
        return "—"
    p = sum(v) / len(v)
    return f"{p:.3f} ±{1.96 * math.sqrt(max(p * (1 - p), 1e-9) / len(v)):.2f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="reports/blt_weak")
    a = ap.parse_args()
    nch = {}
    for l in open(f"{a.root}/data/mc_items.jsonl"):
        r = json.loads(l)
        nch[(r["task"], r["idx"])] = len(r["choices"])
    S = defaultdict(dict)
    for f in glob.glob(f"{a.root}/results/**/echo_*.jsonl", recursive=True):
        for l in open(f):
            r = json.loads(l)
            if r.get("score") is not None and r["cond"] in ("clean", "echo_all"):
                S[r["tag"]][(r["cond"], r["length"], r["pos"])] = r

    def rows(tag, cond, tasks, k):
        return [r for (c, m, i), r in S[tag].items() if c == cond and m in tasks and nch[(m, i)] == k]

    out = []
    for title, tasks, k in (("4-option items: ARC-E + ARC-C + HellaSwag", ("arc_easy", "arc_challenge", "hellaswag"), 4),
                            ("4-option items: ARC-E + ARC-C only (HellaSwag excluded)", ("arc_easy", "arc_challenge"), 4),
                            ("2-option items: PIQA", ("piqa",), 2)):
        out.append(f"## {title}\n")
        n_pos = [len([r for r in rows("blt_1b", "clean", tasks, k) if r["gold"] == p]) for p in range(k)]
        out.append("n per gold position: " + ", ".join(f"{L[p]} {n_pos[p]}" for p in range(k)) + "\n")
        for cond, lab in (("echo_all", "options listed before the question (echo_all)"), ("clean", "clean (no listing, control)")):
            out.append(f"**Accuracy — {lab}**\n")
            out.append("| gold position | " + " | ".join(n for _, n in MODELS) + " |")
            out.append("|---|" + "---:|" * len(MODELS))
            for p in range(k):
                out.append(f"| {L[p]} ({p + 1}{'st' if p == 0 else 'nd' if p == 1 else 'rd' if p == 2 else 'th'}) | "
                           + " | ".join(cell([r["score"] for r in rows(t, cond, tasks, k) if r["gold"] == p])
                                        for t, _ in MODELS) + " |")
            out.append("| all | " + " | ".join(cell([r["score"] for r in rows(t, cond, tasks, k)]) for t, _ in MODELS)
                       + " |")
            out.append("| max − min | " + " | ".join(
                (lambda acc: f"{max(acc) - min(acc):.3f}")([sum(r["score"] for r in rows(t, cond, tasks, k) if r["gold"] == p)
                                                           / max(1, n_pos[p]) for p in range(k)]) for t, _ in MODELS) + " |\n")
        out.append("**Prediction distribution under echo_all (share of items predicted at each position)**\n")
        out.append("| predicted position | " + " | ".join(n for _, n in MODELS) + " |")
        out.append("|---|" + "---:|" * len(MODELS))
        for p in range(k):
            out.append(f"| {L[p]} | " + " | ".join(
                (lambda v: f"{sum(r['pred'] == p for r in v) / len(v):.3f}" if v else "—")(rows(t, "echo_all", tasks, k))
                for t, _ in MODELS) + " |")
        out.append("")
    print("# Accuracy by gold position (five main models)\n")
    print("Generated by `scripts/probes/blt_weak/position_table.py`. Cells: accuracy ±95% half-width.\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
