#!/usr/bin/env python3
"""RESULTS3.md for EXPERIMENTS_3.md: probe3 (E1 + groups A-D, five models), the 2nd-batch echo probe with
H-Net added, the E2 segmentation transplant (BLT), and gold-option patch counts.

All deltas are paired on the same item (ARC-E / ARC-C / PIQA / HellaSwag x 500). DiD = BLT's delta minus the
other model's delta, 95% CI from an item bootstrap (2000 draws, seed 0).

  python scripts/probes/blt_weak/report3.py --root reports/blt_weak
"""
import argparse
import glob
import json
import random
from collections import defaultdict
from pathlib import Path

MODELS = [("subword_llama", "Llama"), ("aunet_static", "AU-Net"), ("byte_greedyroot", "BPEByte"),
          ("hnet_1stage_XL", "H-Net"), ("blt_1b", "BLT-1B")]
GROUPS = [
    ("E1 distance (Δ vs clean_fill)", ["echo_all_near", "echo_all_far", "echo_wrong_near", "echo_wrong_far"], "clean_fill"),
    ("E1 filler alone", ["clean_fill"], "clean"),
    ("A irrelevant / in-domain distractors", ["dist1", "dist2", "dist4", "indomain"], "clean"),
    ("B wrong answer as information", ["soft_wrong", "student_wrong", "neg_wrong", "neg_gold"], "clean"),
    ("C string overlap with a wrong option", ["pre25", "pre50", "pre75", "suf50", "bow"], "clean"),
    ("D listing order", ["list_gold_first", "list_gold_last", "list_two"], "clean"),
    ("2nd batch echo (reference, H-Net added)", ["echo_all", "echo_gold", "echo_wrong", "repeat_q"], "clean"),
]
WRONG_CONDS = ["echo_wrong_near", "echo_wrong_far", "soft_wrong", "student_wrong", "neg_wrong", "pre25", "pre50",
               "pre75", "suf50", "bow"]


def table(head, body):
    return ("| " + " | ".join(head) + " |\n|" + "|".join("---" if i == 0 else "---:" for i in range(len(head)))
            + "|\n" + "".join("| " + " | ".join(map(str, r)) + " |\n" for r in body))


def mean(v):
    return sum(v) / len(v) if v else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="reports/blt_weak")
    a = ap.parse_args()
    root = Path(a.root)
    # scores[tag][(cond, mc, idx)] = row ; echo/clean + probe3 share (mc, idx)
    S = defaultdict(dict)
    for f in glob.glob(f"{root}/results/**/*.jsonl", recursive=True):
        if not any(k in f for k in ("probe3_", "echo_")):
            continue
        for l in open(f):
            r = json.loads(l)
            if r.get("score") is not None and r.get("task") in ("echo", "probe3"):
                S[r["tag"]][(r["cond"], r["length"], r["pos"])] = r
    meta = {}
    for l in open(root / "data/probe3.jsonl"):
        r = json.loads(l)
        meta[(r["cond"], r["length"], r["pos"])] = r["wrong_idx"]
    rng = random.Random(0)

    def delta_items(tag, cond, base):
        return [(m, i) for (c, m, i) in S[tag] if c == cond and (base, m, i) in S[tag]]

    def delta(tag, cond, base, items=None):
        items = items or delta_items(tag, cond, base)
        return mean([S[tag][(cond, m, i)]["score"] - S[tag][(base, m, i)]["score"] for m, i in items]), items

    def did_ci(cond, base, other, cond2=None):
        """BLT delta - other delta on common items; cond2: second-order (cond - cond2) instead of vs base."""
        items = [x for x in delta_items("blt_1b", cond, base) if (cond, *x) in S[other] and (base, *x) in S[other]]
        if cond2:
            items = [x for x in items if all((cond2, *x) in S[t] for t in ("blt_1b", other))]
        if not items:
            return "—"

        def f(its):
            def d(t):
                b = cond2 or base
                return sum(S[t][(cond, m, i)]["score"] - S[t][(b, m, i)]["score"] for m, i in its) / len(its)
            return d("blt_1b") - d(other)
        b = sorted(f([rng.choice(items) for _ in items]) for _ in range(2000))
        p, lo, hi = f(items), b[50], b[1949]
        return f"{p:+.3f}{' **' if lo > 0 or hi < 0 else ''} [{lo:+.3f}, {hi:+.3f}]"

    md = ["# BLT echo follow-up (EXPERIMENTS_3.md) — results\n",
          "Generated by `scripts/probes/blt_weak/report3.py`. Paired Δ on the same items; DiD = BLT Δ − model Δ "
          "(item bootstrap 95% CI, ** = excludes 0). Rows scored: "
          + ", ".join(f"{n} {len(S[t])}" for t, n in MODELS) + ".\n"]
    for title, conds, base in GROUPS:
        md.append(f"## {title}\n")
        body = []
        for c in conds:
            line = [c]
            for t, _ in MODELS:
                d, its = delta(t, c, base)
                line.append(f"{d:+.3f}" if its else "—")
            line += [did_ci(c, base, "byte_greedyroot"), did_ci(c, base, "hnet_1stage_XL")]
            body.append(line)
        md.append(table(["cond"] + [f"Δ {n}" for _, n in MODELS] + ["DiD BLT−BPEByte", "DiD BLT−H-Net"], body))
    # E1 second-order: (far - near) for BLT vs others
    md.append("## E1 key test: far − near (echo moved outside BLT's 512-B windows)\n")
    md.append("Positive = moving the echo away helps. If patch merging drives BLT's excess loss, BLT's far − near should\n"
              "exceed the other models' (DiD-of-DiD > 0).\n")
    body = []
    for kind in ("echo_all", "echo_wrong"):
        line = [kind]
        for t, _ in MODELS:
            items = [(m, i) for (c, m, i) in S[t] if c == f"{kind}_far" and (f"{kind}_near", m, i) in S[t]]
            line.append(f"{mean([S[t][(kind + '_far', m, i)]['score'] - S[t][(kind + '_near', m, i)]['score'] for m, i in items]):+.3f}"
                        if items else "—")
        for o in ("byte_greedyroot", "hnet_1stage_XL", "subword_llama"):
            line.append(did_ci(f"{kind}_far", "clean_fill", o, cond2=f"{kind}_near"))
        body.append(line)
    md.append(table(["echo"] + [f"far−near {n}" for _, n in MODELS] + ["DiD² BLT−BPEByte", "DiD² BLT−H-Net",
                                                                       "DiD² BLT−Llama"], body))
    # attraction to the echoed wrong option
    md.append("## Attraction: share of predictions on the echoed wrong option (Δ vs the same option under clean)\n")
    body = []
    for c in WRONG_CONDS:
        line = [c]
        for t, _ in MODELS:
            v = [(S[t][(c, m, i)]["pred"] == meta[(c, m, i)]) - (S[t][("clean", m, i)]["pred"] == meta[(c, m, i)])
                 for (cc, m, i) in S[t] if cc == c and ("clean", m, i) in S[t]]
            line.append(f"{mean(v):+.3f}" if v else "—")
        body.append(line)
    md.append(table(["cond"] + [n for _, n in MODELS], body))
    # first-listed pick rate
    md.append("## Listing order: accuracy (gold listed first vs last)\n")
    body = []
    for c in ("clean", "echo_all", "list_gold_first", "list_gold_last"):
        line = [c]
        for t, _ in MODELS:
            v = [r for (cc, m, i), r in S[t].items() if cc == c]
            line.append(f"{mean([r['score'] for r in v]):.3f}" if v else "—")
        body.append(line)
    md.append(table(["cond (accuracy)"] + [n for _, n in MODELS], body))
    # patches
    P = defaultdict(dict)
    for f in glob.glob(f"{root}/patches/p3_*.jsonl") + glob.glob(f"{root}/patches/b2_*.jsonl"):
        for l in open(f):
            r = json.loads(l)
            if "answer" in r:
                P[r["tag"]][r["cond"]] = P[r["tag"]].get(r["cond"], []) + [r["answer"]["patches"]]
    if P:
        md.append("## Mechanism: boundaries inside the gold option (mean)\n")
        conds = ["clean", "clean_fill", "echo_all", "echo_all_near", "echo_all_far", "echo_wrong", "echo_wrong_near",
                 "echo_wrong_far", "pre50", "suf50", "bow", "neg_gold", "dist4"]
        md.append(table(["cond", "BLT", "BPEByte"],
                        [[c] + [f"{mean(P[t].get(c, [])):.2f}" if P[t].get(c) else "—"
                                for t in ("blt_1b", "byte_greedyroot")] for c in conds]))
    # E2 transplant
    T = defaultdict(dict)
    for f in glob.glob(f"{root}/results/**/transplant_blt_1b*.jsonl", recursive=True):
        for l in open(f):
            r = json.loads(l)
            T[r["cond"]][(r["mc"], r["idx"])] = r
    if T:
        md.append("## E2 segmentation transplant (BLT only; bytes fixed, option-span boundaries swapped)\n")
        body = []
        for c in ("clean_nat", "clean_echoseg", "clean_byte", "echo_nat", "echo_cleanseg", "echo_byte"):
            v = list(T[c].values())
            if not v:
                continue
            nonhs = [r for r in v if r["mc"] != "hellaswag"]
            body.append([c, len(v), f"{mean([r['score'] for r in v]):.3f}",
                         f"{mean([r['pred'] == 0 for r in nonhs]):.3f}"])
        md.append(table(["cond", "n", "acc", "pred = first listed (non-HS)"], body))
        md.append("\nPaired effects:\n")
        body = []
        for a_, b_ in (("echo_cleanseg", "echo_nat"), ("echo_byte", "echo_nat"), ("clean_echoseg", "clean_nat"),
                       ("clean_byte", "clean_nat"), ("echo_nat", "clean_nat"), ("echo_cleanseg", "clean_nat")):
            ks = [k for k in T[a_] if k in T[b_]]
            if not ks:
                continue
            f = lambda xs: mean([T[a_][k]["score"] - T[b_][k]["score"] for k in xs])
            bs = sorted(f([rng.choice(ks) for _ in ks]) for _ in range(2000))
            body.append([f"{a_} − {b_}", len(ks), f"{f(ks):+.3f}", f"[{bs[50]:+.3f}, {bs[1949]:+.3f}]"])
        md.append(table(["contrast", "n", "Δacc", "95% CI"], body))
    (root / "RESULTS3.md").write_text("\n".join(md) + "\n")
    print("wrote", root / "RESULTS3.md")


if __name__ == "__main__":
    main()
