#!/usr/bin/env python3
"""Aggregate the BLT-weakness probes (results/*.jsonl from run_node.sh, patches/*.jsonl from
patch_probe.py) into reports/blt_weak/RESULTS.md tables + dist512 / count figures.

Rows are deduplicated on (tag, id) across shards / nodes; crashed rows (score None) are dropped
and counted. Cells show acc with a 95% normal-approx half-width.

  python scripts/probes/blt_weak/report.py --root reports/blt_weak
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import statistics as st
from collections import defaultdict
from pathlib import Path

MODELS = [("subword_llama", "Llama"), ("aunet_static", "AU-Net"), ("byte_greedyroot", "BPEByte"),
          ("blt_1b", "BLT-1B")]
PT_MODELS = [("blt_1b", "BLT"), ("byte_greedyroot", "BPEByte"), ("aunet_static", "AU-Net")]


def load(root):
    rows, crashed = {}, defaultdict(int)
    for f in sorted(glob.glob(f"{root}/results/**/*.jsonl", recursive=True)):
        for line in open(f):
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("score") is None:
                crashed[r["tag"]] += 1
                continue
            rows[(r["tag"], r["id"])] = r
    return list(rows.values()), crashed


def load_patches(root):
    out = {}
    for f in glob.glob(f"{root}/patches/*.jsonl"):
        for line in open(f):
            r = json.loads(line)
            out[(r["tag"], r["id"])] = r
    return out


def cell(v):
    if not v:
        return "—"
    p = sum(v) / len(v)
    h = 1.96 * math.sqrt(max(p * (1 - p), 1e-9) / len(v))
    return f"{p:.3f} ±{h:.2f}"


def mean(v):
    return sum(v) / len(v) if v else float("nan")


def table(head, body):
    s = "| " + " | ".join(head) + " |\n|" + "|".join("---" if i == 0 else "---:" for i in range(len(head))) + "|\n"
    return s + "".join("| " + " | ".join(map(str, r)) + " |\n" for r in body)


def group(rows, task_pred):
    g = defaultdict(list)
    for r in rows:
        if task_pred(r["task"]):
            g[(r["task"], r["cond"], r["length"], r["tag"])].append(r["score"])
    return g


def acc_table(g, keys, label):
    """keys: [(row_label, [(task, cond, length), ...])] pooled per row."""
    body = []
    for lab, ks in keys:
        line = [lab]
        for tag, _ in MODELS:
            v = [x for k in ks for x in g.get((*k, tag), [])]
            line.append(cell(v))
        n = max(len([x for k in ks for x in g.get((*k, tag), [])]) for tag, _ in MODELS)
        body.append(line + [n])
    return table([label] + [m for _, m in MODELS] + ["n"], body)


def delta_table(g, pairs, label):
    """pairs: [(row_label, keys_treat, keys_ref)] -> acc(treat) - acc(ref) per model."""
    body = []
    for lab, kt, kr in pairs:
        line = [lab]
        for tag, _ in MODELS:
            t = [x for k in kt for x in g.get((*k, tag), [])]
            r = [x for k in kr for x in g.get((*k, tag), [])]
            line.append(f"{mean(t) - mean(r):+.3f}" if t and r else "—")
        body.append(line)
    return table([label] + [m for _, m in MODELS], body)


def patch_table(P, rows_by_id, pred, groups, spans):
    """Mean patches / longest run over the rows of each group for each span, per parser."""
    body = []
    for lab, gp in groups:
        line = [lab]
        for tag, _ in PT_MODELS:
            for sp in spans:
                v = [P[(tag, i)][sp] for i, r in rows_by_id.items()
                     if pred(r) and gp(r) and (tag, i) in P and sp in P[(tag, i)]]
                line.append(f"{mean([x['patches'] for x in v]):.1f} / {mean([x['bytes'] for x in v]):.0f}"
                            if v else "—")
        body.append(line)
    head = [""] + [f"{m} {sp}" for _, m in PT_MODELS for sp in spans]
    return table(head, body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="reports/blt_weak")
    a = ap.parse_args()
    root = Path(a.root)
    rows, crashed = load(root)
    P = load_patches(root)
    data = {}
    for f in glob.glob(f"{root}/data/*.jsonl"):
        for line in open(f):
            r = json.loads(line)
            if "id" in r:
                data[r["id"]] = r
    have = defaultdict(int)
    for r in rows:
        have[r["tag"]] += 1
    md = ["# BLT weakness probes — results\n",
          "Generated by `scripts/probes/blt_weak/report.py`. Candidates and rationale: `CANDIDATES.md`.",
          "All four models score byte-identical prompts (`data/*.jsonl`, built by `build_tasks.py`) with",
          "`run_longctx.py` (greedy decode cut to `window` bytes, `substr` match; count = argmax log P",
          "over the 20 count options). BLT-1B = official bytelatent + xformers, bs 1, prompt+gen ≤ 4096 B.",
          "Cells: accuracy ±95% half-width. Rows scored: "
          + ", ".join(f"{m} {have[t]}" for t, m in MODELS)
          + (f". Crashed (dropped): {dict(crashed)}" if crashed else "") + ".\n"]

    # ---- hashhop
    g = group(rows, lambda t: t == "hashhop")
    Ls = sorted({k[2] for k in g})
    md += ["## 1. HashHop hops=1 (BLT arm)\n",
           acc_table(g, [(f"{L} B", [("hashhop", "h1", L)]) for L in Ls], "haystack")]
    # ---- MK-NIAH word
    g = group(rows, lambda t: t.startswith("mkniah"))
    md += ["## 2. MK-NIAH (RULER word keys, 2 KB) — BLT arm\n",
           acc_table(g, [(f"K={K}", [("mkniah_word", f"K{K}", 2048)]) for K in (1, 2, 4, 8)], "needles")]
    # ---- MK-NIAH near-collision
    modes = ["rand", "nc_first", "nc_mid", "nc_last"]
    md += ["## 3. Near-collision MK-NIAH (8-char code keys, 2 KB)\n",
           "`rand` = independent random keys; `nc_*` = every distractor key equals the target key with one",
           "character substituted at the first / middle / last position.\n",
           acc_table(g, [(f"{m} K={K}", [("mkniah_nc", f"{m}_K{K}", 2048)]) for m in modes for K in (2, 4, 8)],
                     "keys"),
           "\nΔ vs `rand` (pooled over K):\n",
           delta_table(g, [(m, [("mkniah_nc", f"{m}_K{K}", 2048) for K in (2, 4, 8)],
                            [("mkniah_nc", f"rand_K{K}", 2048) for K in (2, 4, 8)]) for m in modes[1:]], "mode")]
    # ---- S-NIAH near-collision
    g = group(rows, lambda t: t.startswith("sniah"))
    conds = ["clean", "distract", "key_nc", "keyval_nc"]
    Ls = sorted({k[2] for k in g})
    md.append("## 4. S-NIAH-1/2/3 + near-collision distractors\n")
    md.append("`distract` = 3 extra needles with unrelated keys; `key_nc` = 3 extra needles whose key is one letter\n"
              "off the target key (first letter kept); `keyval_nc` = key_nc + values equal to gold except the tail\n"
              "(last 2 digits / last 4 hex).\n")
    for t in ("1", "2", "3"):
        task = f"sniah{t}_nc"
        md.append(f"### S-NIAH-{t}\n")
        md.append(acc_table(g, [(f"{c} (all L)", [(task, c, L) for L in Ls]) for c in conds]
                            + [(f"{c} {L}", [(task, c, L)]) for c in conds for L in Ls], "cond"))
        md.append("\nΔ vs clean:\n")
        md.append(delta_table(g, [(c, [(task, c, L) for L in Ls], [(task, "clean", L) for L in Ls])
                                  for c in conds[1:]], "cond"))
    md.append("### S-NIAH mean over tasks 1–3, Δ vs clean\n")
    md.append(delta_table(g, [(c, [(f"sniah{t}_nc", c, L) for t in "123" for L in Ls],
                               [(f"sniah{t}_nc", "clean", L) for t in "123" for L in Ls]) for c in conds[1:]],
                          "cond"))
    # ---- count
    gc = defaultdict(list)
    for r in rows:
        if r["task"] == "count":
            gc[(r["cond"], r["tag"])].append(r)
    md.append("## 5. Repetition counting (few-shot, gold 2–15, 20 options)\n")
    body = []
    for c in ("word", "char", "digit", "chunk_sep", "chunk_nosep"):
        line = [c]
        for tag, _ in MODELS:
            v = gc.get((c, tag), [])
            line.append(f"{cell([x['score'] for x in v])} · MAE {mean([abs(x['pred'] - x['gold']) for x in v]):.2f}"
                        if v else "—")
        body.append(line)
    md.append(table(["unit"] + [m for _, m in MODELS], body))
    md.append("\nAccuracy by gold count bucket (all units pooled):\n")
    body = []
    for lo, hi in ((2, 5), (6, 10), (11, 15)):
        line = [f"{lo}–{hi}"]
        for tag, _ in MODELS:
            v = [x["score"] for (c, t), xs in gc.items() if t == tag for x in xs if lo <= x["gold"] + 1 <= hi]
            line.append(cell(v))
        body.append(line)
    md.append(table(["count"] + [m for _, m in MODELS], body))
    # ---- copy
    g = group(rows, lambda t: t == "copy")
    md.append("## 6. Verbatim copy (3-shot)\n")
    md.append(acc_table(g, [(f"{c} L={L}", [("copy", c, L)]) for c in ("rand", "periodic", "periodic_mut", "words_mut")
                            for L in (32, 64, 128)], "string"))
    # ---- dist512
    g = group(rows, lambda t: t == "dist512")
    ds = sorted({k[2] for k in g})
    md.append("## 7. Needle–query distance sweep (fixed ~3.5 KB context)\n")
    for c in ("hash", "num"):
        md.append(f"### {c} needle\n")
        md.append(acc_table(g, [(f"d={d}", [("dist512", c, d)]) for d in ds], "distance"))
        md.append("\n<=512 vs >512 (pooled):\n")
        md.append(acc_table(g, [("d ≤ 512", [("dist512", c, d) for d in ds if d <= 512]),
                                ("d > 512", [("dist512", c, d) for d in ds if d > 512])], "bucket"))
    # ---- patches
    if P:
        md.append("## 8. Mechanism: patches spent on the critical spans\n")
        md.append("Cells: mean boundaries inside the span / mean span bytes (patches ±1). `nkey` = key in the needle,\n"
                  "`qkey1` = first query mention (d bytes after the needle), `answer` = gold continuation.\n")
        md.append("### dist512\n")
        for c in ("hash", "num"):
            md.append(f"{c}:\n")
            md.append(patch_table(P, data, lambda r, c=c: r["task"] == "dist512" and r["cond"] == c,
                                  [(f"d={d}", lambda r, d=d: r["length"] == d) for d in ds],
                                  ["nkey", "qkey1", "answer"]))
        md.append("### count (string being counted)\n")
        md.append(patch_table(P, data, lambda r: r["task"] == "count",
                              [(c, lambda r, c=c: r["cond"] == c) for c in
                               ("word", "char", "digit", "chunk_sep", "chunk_nosep")], ["text"]))
        md.append("### copy (string to copy)\n")
        md.append(patch_table(P, data, lambda r: r["task"] == "copy",
                              [(f"{c} L={L}", lambda r, c=c, L=L: r["cond"] == c and r["length"] == L)
                               for c in ("rand", "periodic", "periodic_mut", "words_mut") for L in (32, 128)],
                              ["text", "answer"]))
        md.append("### near-collision MK-NIAH (query key / answer)\n")
        md.append(patch_table(P, data, lambda r: r["task"] == "mkniah_nc",
                              [(m, lambda r, m=m: r["cond"].startswith(m)) for m in modes],
                              ["qkey1", "answer"]))
    md += batch2(rows, P, root)
    (root / "RESULTS.md").write_text("\n".join(md) + "\n")
    print(f"wrote {root / 'RESULTS.md'}")
    plot(rows, P, data, root)


MC = ["arc_easy", "arc_challenge", "piqa", "hellaswag"]
OOD = ["en", "code", "zh", "te", "random_ascii", "hex", "base64", "uuid", "json_log", "csv", "boilerplate",
       "repeat_line"]


def batch2(rows, P, root):
    """Sections 9-12: echo / priming (#3), byte insertions (#5), OOD compute (#4), determinism (#6)."""
    md = []
    sc = defaultdict(dict)                       # (tag) -> {(task, cond, mc, idx): score}
    for r in rows:
        if r["task"] in ("echo", "insert"):
            sc[r["tag"]][(r["task"], r["cond"], r["length"], r["pos"])] = r["score"]
    if sc:
        def acc(tag, task, cond, mcs=MC):
            v = [x for (t, c, m, _), x in sc[tag].items() if t == task and c == cond and m in mcs]
            return v

        def paired_delta(tag, task, cond, mcs=MC):
            """acc(cond) - acc(clean) over items scored in both (clean = echo/clean)."""
            d = [x - sc[tag][("echo", "clean", m, i)] for (t, c, m, i), x in sc[tag].items()
                 if t == task and c == cond and m in mcs and ("echo", "clean", m, i) in sc[tag]]
            return f"{mean(d):+.3f}" if d else "—"

        for task, conds, title in (
                ("echo", ["clean", "echo_all", "echo_gold", "echo_wrong", "repeat_q"],
                 "## 9. Echo / priming (#3) — ARC-E / ARC-C / PIQA / HellaSwag, 500 items each, raw-loglik acc"),
                ("insert", ["zwsp", "shy", "nbsp", "emoji", "homoglyph"],
                 "## 10. Semantics-preserving byte insertions (#5) — same items, question text only")):
            md.append(title + "\n")
            body = [[c] + [cell(acc(tag, task, c)) for tag, _ in MODELS] for c in conds]
            if task == "insert":
                body.insert(0, ["clean"] + [cell(acc(tag, "echo", "clean")) for tag, _ in MODELS])
            md.append(table(["variant (4 tasks pooled)"] + [m for _, m in MODELS], body))
            md.append("\nPaired Δ vs clean (pooled; per task below):\n")
            body = [[c] + [paired_delta(tag, task, c) for tag, _ in MODELS] for c in conds if c != "clean"]
            md.append(table(["variant"] + [m for _, m in MODELS], body))
            body = [[f"{c} / {m}"] + [paired_delta(tag, task, c, [m]) for tag, _ in MODELS]
                    for c in conds if c != "clean" for m in MC]
            md.append("\n<details><summary>per task</summary>\n\n" +
                      table(["variant / task"] + [n for _, n in MODELS], body) + "\n</details>\n")
            # mechanism: patch density of the prompt (insert) / patches on the gold option (echo)
            pt = defaultdict(lambda: defaultdict(list))
            for (tag, i), p in P.items():
                if not i.startswith(("echo-", "ins-")):
                    continue
                pt[tag][p["cond"]].append(p)
            if pt:
                if task == "echo":
                    md.append("\nPatches on the gold option (mean boundaries / bytes):\n")
                    body = [[c] + [(lambda v: f"{mean([x['answer']['patches'] for x in v]):.2f} / "
                                              f"{mean([x['answer']['bytes'] for x in v]):.1f}" if v else "—")(
                        pt[tag].get(c, [])) for tag, _ in PT_MODELS] for c in conds]
                else:
                    md.append("\nPrompt bytes per patch (higher = coarser; clean = echo/clean):\n")
                    body = [[c] + [(lambda v: f"{sum(x['n_bytes'] for x in v) / max(1, sum(x['n_patches'] for x in v)):.2f}"
                                    if v else "—")(pt[tag].get(c, [])) for tag, _ in PT_MODELS]
                            for c in ["clean"] + conds]
                md.append(table(["variant"] + [m for _, m in PT_MODELS], body))
    # ---- 11. OOD compute
    W = [r for r in rows if r["task"] == "ood"]
    if W:
        md.append("## 11. Out-of-distribution inputs (#4) — 3000-byte windows, 40 per domain\n")
        md.append("Bytes per patch (BLT entropy patcher, BPEByte / AU-Net parser) and bytes per token (Llama).\n"
                  "Lower = more global-model positions per byte = more compute.\n")
        win = defaultdict(lambda: defaultdict(list))
        for (tag, i), p in P.items():
            if i.startswith("ood-") and "domain" in p:
                win[tag][p["domain"]].append(p)
        tags = [("blt_1b", "BLT"), ("byte_greedyroot", "BPEByte"), ("aunet_static", "AU-Net"),
                ("subword_llama", "Llama (tok)")]
        body = []
        for d in OOD:
            line = [d]
            for tag, _ in tags:
                v = win[tag].get(d, [])
                line.append(f"{sum(x['n_bytes'] for x in v) / max(1, sum(x['n_patches'] for x in v)):.2f}" if v else "—")
            body.append(line)
        md.append(table(["domain"] + [n for _, n in tags], body))
        md.append("\nWorst-case drift vs English, |log2(B/patch_domain / B/patch_en)| (max over domains):\n")
        line = ["max |log2 ratio|"]
        for tag, _ in tags:
            def bpp(d):
                v = win[tag].get(d, [])
                return sum(x["n_bytes"] for x in v) / max(1, sum(x["n_patches"] for x in v)) if v else None
            en = bpp("en")
            rs = [(abs(math.log2(bpp(d) / en)), d) for d in OOD if en and bpp(d)]
            line.append(f"{max(rs)[0]:.2f} ({max(rs)[1]})" if rs else "—")
        md.append(table(["", *[n for _, n in tags]], [line]))
        md.append("\nBPB (summed log-prob of the window with an empty prompt / bytes):\n")
        g = defaultdict(list)
        for r in W:
            g[(r["tag"], r["cond"])].append((-r["lls"][0], r["length"]))
        body = [[d] + [(lambda v: f"{sum(a for a, _ in v) / (math.log(2) * sum(b for _, b in v)):.3f}" if v else "—")(
            g.get((tag, d), [])) for tag, _ in MODELS] for d in OOD]
        md.append(table(["domain"] + [m for _, m in MODELS], body))
        lat = {}
        for f in glob.glob(f"{root}/latency/*.jsonl"):
            for line in open(f):
                x = json.loads(line)
                lat[(x["tag"], x["domain"])] = x["ms_median"]
        if lat:
            md.append("\nScoring latency, one 3000-byte window, bs 1, same A100 (median ms over 8 windows x 3 reps):\n")
            body = [[d] + [f"{lat[(tag, d)]:.0f}" if (tag, d) in lat else "—" for tag, _ in MODELS] for d in OOD]
            md.append(table(["domain"] + [m for _, m in MODELS], body))
        # ---- 12. determinism
        md.append("## 12. Boundary determinism (#6) — same 480 windows\n")
        md.append("Per perturbation: % of windows with >= 1 flipped boundary · mean flipped boundaries per window.\n"
                  "`prefix` = boundaries of the first half fed alone vs the same span inside the full window (streaming);\n"
                  "`pad` = +1024 trailing pad bytes; `batch8` = patched in a batch with 7 other windows; `fp32` = fp32\n"
                  "entropy model; `recompute` = same call twice.\n")
        body = []
        for tag, name in (("blt_1b", "BLT"), ("byte_greedyroot", "BPEByte"), ("aunet_static", "AU-Net")):
            v = [p for d in OOD for p in win[tag].get(d, [])]
            line = [name]
            for k in ("flip_recompute", "flip_prefix", "flip_pad", "flip_batch8", "flip_fp32"):
                x = [p[k] for p in v if k in p]
                line.append(f"{100 * mean([y > 0 for y in x]):.0f}% · {mean(x):.2f}" if x else "n/a")
            body.append(line)
        md.append(table(["parser", "recompute", "prefix", "pad", "batch8", "fp32"], body))
        md.append("\nBLT flips by domain (mean flipped boundaries per window: prefix / pad / batch8 / fp32):\n")
        body = []
        for d in OOD:
            v = win["blt_1b"].get(d, [])
            body.append([d] + [f"{mean([p[k] for p in v]):.2f}" if v else "—"
                               for k in ("flip_prefix", "flip_pad", "flip_batch8", "flip_fp32")])
        md.append(table(["domain", "prefix", "pad", "batch8", "fp32"], body))
    return md


def plot(rows, P, data, root):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return
    colors = {"subword_llama": "#7f7f7f", "aunet_static": "#2a9d8f", "byte_greedyroot": "#e76f51",
              "blt_1b": "#264653"}
    fig, axes = plt.subplots(1, 3, figsize=(13, 3.6))
    for ax, c in zip(axes[:2], ("hash", "num")):
        for tag, name in MODELS:
            g = defaultdict(list)
            for r in rows:
                if r["task"] == "dist512" and r["cond"] == c and r["tag"] == tag:
                    g[r["length"]].append(r["score"])
            if g:
                ds = sorted(g)
                ax.plot(ds, [mean(g[d]) for d in ds], "o-", ms=3, label=name, color=colors[tag])
        ax.axvline(512, ls="--", c="k", lw=0.8)
        ax.set_xscale("log", base=2)
        ax.set_title(f"dist512 / {c} needle")
        ax.set_xlabel("needle → query distance (bytes)")
        ax.set_ylabel("exact match")
        ax.legend(fontsize=7)
    ax = axes[2]
    for tag, name in PT_MODELS:
        for sp, ls in (("answer", "-"), ("qkey1", ":")):
            g = defaultdict(list)
            for (t, i), p in P.items():
                r = data.get(i)
                if t == tag and r and r["task"] == "dist512" and r["cond"] == "hash" and sp in p:
                    g[r["length"]].append(p[sp]["patches"])
            if g:
                ds = sorted(g)
                ax.plot(ds, [mean(g[d]) for d in ds], ls, marker="o", ms=3, label=f"{name} {sp}",
                        color=colors[tag])
    ax.axvline(512, ls="--", c="k", lw=0.8)
    ax.set_xscale("log", base=2)
    ax.set_title("patches on 12-B span (hash)")
    ax.set_xlabel("needle → query distance (bytes)")
    ax.legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(root / "dist512.png", dpi=150)
    print(f"wrote {root / 'dist512.png'}")


if __name__ == "__main__":
    main()
