#!/usr/bin/env python3
"""tab:niah_aunet (main, by distance to the query) and tab:niah_variants (appendix, by context length) from
reports/niah/needle_variants/summary.json (needle_variants_summary.py). Every row uses the S-NIAH-3 items of the
final set (essay haystack, 0.5k/1k/2k + fit-4k, 250 per length) with only the needle value changed."""
import json, os
from pathlib import Path
L = Path("/mnt/ssd2/hyun2/AUNet"); OVL = Path(os.environ.get("PAPER_DIR", L / "paper_overleaf"))
S = json.load(open(L / "reports/niah/needle_variants/summary.json"))
GEN = "% GENERATED by AUNet/scripts/niah/make_needle_variant_tables.py — edit the script, not this file."
ROWS = [("num7", "7-digit number", "(S-NIAH-2)"), ("uuid", "UUID", "(S-NIAH-3)"), ("uuid_space", "UUID,", "hyphens$\\to$spaces"),
        ("hex32_sp4", "$32$ hex chars,", "space every $4$"), ("digits32", "$32$ random", "digits"),
        ("letters32", "$32$ random", "letters"),
        ("tok4", "$7{\\times}4$ letters,", "BPE tokens"), ("rand4", "$7{\\times}4$ letters,", "random")]
MAIN = ("num7", "uuid", "tok4", "rand4")           # tab:niah_aunet rows (the paper dropped the others to the appendix)
NM = {"aunet": "AUNet", "bpebyte": "BPEByte", "llama": "Transformer"}
f2 = lambda x: f"${100 * x:.1f}$"                   # accuracy in %
allm = lambda s: sum(s["len"].values()) / 4        # mean of the four length means, as tab:sniah_full


def main_table():
    n = S["uuid|aunet"]["bins"]
    t = [GEN, r"\begin{table}[!t]", r"\centering",
         r"\caption{\hyun{S-NIAH exact match of AUNet and BPEByte at 1B by needle value. Every row uses the same "
         r"$1{,}000$ S-NIAH-3 items (essay haystack, the four context lengths of Table~\ref{tab:sniah_full}) and changes "
         r"only the needle value; the 7-digit and UUID rows are S-NIAH-2 and S-NIAH-3 themselves. B/patch is the value "
         r"length divided by the number of parsing units that cover it, and ${\\geq}$4B the share of value bytes (\\%) in "
         r"units of at least four bytes. Distance is the number of haystack bytes between "
         f"the needle and the query ($(1{{-}}\\text{{depth}}) \\times$ context length; ${n['<256'][1]}$, ${n['256-512'][1]}$, "
         f"and ${n['>=512'][1]}$ items per bin). Appendix~\\ref{{app:niah_variants}} gives the results by context length, "
         r"including the Transformer.}}", r"\label{tab:niah_aunet}",
         r"\small", r"\setlength{\tabcolsep}{3.5pt}", r"\fitcolumn{%",
         r"\begin{tabular}{llcccccc}", r"\toprule",
         r" & & & & \multicolumn{4}{c}{\textbf{Acc (\%)}} \\", r"\cmidrule(lr){5-8}",
         r" & & & & \multicolumn{3}{c}{Distance to query} & \\", r"\cmidrule(lr){5-7}",
         r"\textbf{Needle value} & \textbf{Model} & \textbf{B/patch} & \textbf{${\geq}$4B (\%)} & ${<}256$ & $256$--$512$ & ${\geq}512$ & \textbf{All} \\",
         r"\midrule"]
    for j, (k, a, b) in enumerate([r for r in ROWS if r[0] in MAIN]):
        if j:
            t.append(r"\midrule")
        for i, m in enumerate(("aunet", "bpebyte")):
            s = S[f"{k}|{m}"]; bn = s["bins"]
            t.append(f"{(a, b)[i]} & {NM[m]} & ${s['bpp']:.1f}$ & {f2(s['ge4'])} & " +
                     " & ".join(f2(bn[x][0]) for x in ("<256", "256-512", ">=512")) + f" & {f2(allm(s))}" + r" \\")
    t += [r"\bottomrule", r"\end{tabular}", "}", r"\end{table}", ""]
    (OVL / "tables/niah_aunet.tex").write_text("\n".join(t))


def app_table():
    t = [GEN, r"\begin{table}[t]", r"\centering",
         r"\caption{\hyun{Needle-value variants of S-NIAH by context length ($250$ items per cell; the S-NIAH-3 items with "
         r"only the value changed, Appendix~\ref{app:niah_variants}). B/patch is the value length divided by the number "
         r"of parsing units covering it (the Transformer's subword tokens are not listed). The noun in the needle and the "
         r"query names the value type (number, UUID, or code).}}", r"\label{tab:niah_variants}",
         r"\small", r"\setlength{\tabcolsep}{3pt}", r"\fitcolumn{%",
         r"\begin{tabular}{llcccccc}", r"\toprule",
         r" & & & \multicolumn{5}{c}{\textbf{Acc (\%)}} \\", r"\cmidrule(lr){4-8}",
         r"\textbf{Needle value} & \textbf{Model} & \textbf{B/patch} & \textbf{0.5k} & \textbf{1k} & \textbf{2k} & \textbf{4k} & \textbf{Mean} \\",
         r"\midrule"]
    for j, (k, a, b) in enumerate(ROWS):
        if j:
            t.append(r"\midrule")
        for i, m in enumerate(("llama", "aunet", "bpebyte")):
            s = S[f"{k}|{m}"]
            lab = (a, b, "")[i]
            bpp = "--" if m == "llama" else f"${s['bpp']:.2f}$"
            t.append(f"{lab} & {NM[m]} & {bpp} & " + " & ".join(f2(s["len"][x]) for x in ("512", "1024", "2048", "4096")) +
                     f" & {f2(allm(s))} \\\\")
    t += [r"\bottomrule", r"\end{tabular}", "}", r"\end{table}", ""]
    (OVL / "table_appendix/niah_variants.tex").write_text("\n".join(t))


main_table(); app_table(); print("ok")
