#!/usr/bin/env python3
"""tab:niah_value_examples (paper_overleaf/table_appendix/niah_value_examples.tex): one value per needle format with the AUNet/BPEByte parse.
  PYTHONPATH=lingua lingua/.venv/bin/python scripts/niah/make_needle_value_examples.py"""
import os, sys; sys.path.insert(0,'/mnt/ssd2/hyun2/AUNet/scripts/probes'); sys.path.insert(0,'/mnt/ssd2/hyun2/AUNet/scripts/probes/patch_stats')
OVL=os.environ.get('PAPER_DIR','paper_overleaf')
from compression_stability import build_parser
V=[('num7','0487647'),('uuid','18fc9fb6-4943-8493-2af3-bda6fe8102c0'),('uuid_space','affcbaef b209 fe78 3290 7900f39af60c'),
   ('hex','0db7 7f32 1cba e143 b47c d00d afc9 9bae'),('digits','59287540400471469063340271224236'),('letters','fzfswwvhavslrvhquqdvibnvnyobynes'),
   ('tok4','ruby-empo-cers-quis-itto-orgh-bate'),('rand4','odvx-jppl-flux-wbvh-khrv-ahom-nceo')]  # first items of items_v2.jsonl
P={m:build_parser(m) for m in ('aunet','bpebyte')}
pre='The special magic code for glacier is'
for k,v in V:
  t=pre+' '+v; b=t.encode(); vs=len(b)-len(v.encode())
  for m in P:
    cuts=sorted(set([vs]+[s for s in P[m](t) if vs<s<len(b)]+[len(b)]))
    u=[b[cuts[i]:cuts[i+1]].decode() for i in range(len(cuts)-1)]
    print(k,m,len(u),round(len(v)/len(u),2),'|'.join(u))

def tex(units):
    out=[]
    for u in units:
        for i,c in enumerate(u):
            c = r'\textvisiblespace{}' if c==' ' else c
            out.append((r'\bb{%s}'%c if i==0 else c) + r'\allowbreak{}')
    return ''.join(out)
LAB={'num7':r'7-digit number (S-NIAH-2)','uuid':r'UUID (S-NIAH-3)','uuid_space':r'UUID, hyphens$\to$spaces',
     'hex':r'$32$ hex chars, space every $4$','digits':r'$32$ random digits','letters':r'$32$ random letters',
     'tok4':r'$7{\times}4$ letters, BPE tokens','rand4':r'$7{\times}4$ letters, random'}
NM={'aunet':'AUNet','bpebyte':'BPEByte'}
L=[r"% GENERATED by AUNet/scripts/niah/make_needle_value_examples.py — edit the script, not this file.",
   r'% Example needle values of tab:niah_aunet / tab:niah_variants (one item per row; values from reports/niah/needle_variants/items.jsonl',
   r'% and reports/niah/sniah123_n250_final_pairs.jsonl), parsed by scripts/probes/compression_stability.build_parser after "... is ".',
   r'\begin{table}[tbp]', r'\centering',
   r'\caption{\hyun{One example value of each needle format in Tables~\ref{tab:niah_aunet} and~\ref{tab:niah_variants}, with the parse of AUNet and BPEByte on it. Each highlighted byte starts a parsing unit, and the number of units is in parentheses; \textvisiblespace{} is a space. As in the scored sequence, the value follows \texttt{...\ is} and a space.}}',
   r'\label{tab:niah_value_examples}', r'\small', r'\setlength{\tabcolsep}{3pt}',
   r'\begin{tabular}{@{}lp{0.68\columnwidth}@{}}', r'\toprule',
   r'\textbf{Needle value} & \textbf{Example and parse} \\', r'\midrule']
for j,(k,v) in enumerate(V):
    t=pre+' '+v; b=t.encode(); vs=len(b)-len(v.encode()); rows=[]
    L.append(r'\multicolumn{2}{@{}l@{}}{\emph{%s}} \\' % LAB[k])
    L.append(r'\quad Value & {\raggedright\ttfamily\footnotesize %s\par} \\' % tex([c for c in v]).replace(r'\bb{','{'))
    for m in P:
        cuts=sorted(set([vs]+[s for s in P[m](t) if vs<s<len(b)]+[len(b)]))
        u=[b[cuts[i]:cuts[i+1]].decode() for i in range(len(cuts)-1)]
        L.append(r'\quad %s ($%d$) & {\raggedright\ttfamily\footnotesize %s\par} \\' % (NM[m], len(u), tex(u)))
    if j<len(V)-1: L.append(r'\midrule')
L+= [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(OVL+'/table_appendix/niah_value_examples.tex','w').write('\n'.join(L)+'\n')
