#!/usr/bin/env python3
"""S-NIAH tables and the main-table S-NIAH column from the per-item results, via plot_sniah_heatmap.load().

Tasks: S-NIAH-1/2/3 (final set: 0.5k/1k/2k n=250 + fit-4k cell) and their repeated-haystack variants
S-NIAH-1/2/3-rep (haystack = a 64-byte window of the same source repeated; same key/value/depth and at most the
same scored bytes per item; scripts/niah/dump_sniah_rep_pairs.py).

Writes
  paper_overleaf/table_appendix/niah.tex        tab:sniah_full, per-length recall of all six tasks
  paper_overleaf/table_appendix/sniah_rep.tex   tab:sniah_rep, original vs repeated haystack per model, with the
                                                paired item-bootstrap 95% CI of the change (B=2000, stratified by cell)
  reports/niah/final/sniah_summary.json         per-cell accuracy, overall means (6-task = main-table column)
"""
import json, sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_sniah_heatmap import load, LENS, TASKS, REP  # noqa: E402

L = Path("/mnt/ssd2/hyun2/AUNet")
GEN = "% GENERATED by AUNet/scripts/niah/make_sniah_table.py — edit the script, not this file."
ROWS = [("Transformer", "Transformer  "), ("AUNet", "AUNet "), ("BPEByte (ours)", "BPEByte"),
        ("BLT ($\\theta$=1.34)", "BLT$^{\\dagger}$"), ("H-Net", "H-Net$^{\\ddagger}$")]
CMP_ROWS = [("Transformer", "Transformer"), ("AUNet", "AUNet"), ("BPEByte (ours)", "BPEByte (ours)"),
            ("BLT ($\\theta$=1.34)", "BLT$^{\\dagger}$ ($\\theta{=}1.34$)"),
            ("BLT ($\\theta$=1.61)", "BLT$^{\\dagger}$ ($\\theta{=}1.61$)"), ("H-Net", "H-Net$^{\\ddagger}$")]
LAB = {"sniah1": ("S-NIAH-1", "(number)"), "sniah2": ("S-NIAH-2", "(7-digit)"), "sniah3": ("S-NIAH-3", "(UUID)  "),
       "sniah1r": ("S-NIAH-1-rep", "(number)"), "sniah2r": ("S-NIAH-2-rep", "(7-digit)"),
       "sniah3r": ("S-NIAH-3-rep", "(UUID)")}
ALL = TASKS + REP


def cell_acc(M, m, t, Ln):
    v = M[m][f"{t}/{Ln}"]
    return sum(ok for _, ok in v) / len(v)


def paired(M, m, t, Ln):
    """0/1 arrays of the original and repeated item i (both in depth order (i+0.5)/n)."""
    o = [ok for _, ok in sorted(M[m][f"{t}/{Ln}"])]
    r = [ok for _, ok in sorted(M[m][f"{t}r/{Ln}"])]
    assert len(o) == len(r), (m, t, Ln)
    return np.array(o, float), np.array(r, float)


def boot_delta(M, m, rng, B=2000):
    """Mean over the 12 (task, length) cells of recall(rep) - recall(orig); CI by resampling items within cells."""
    cells = [paired(M, m, t, Ln) for t in TASKS for Ln in LENS]
    d = [r - o for o, r in cells]
    point = np.mean([x.mean() for x in d])
    bs = [np.mean([x[rng.integers(0, len(x), len(x))].mean() for x in d]) for _ in range(B)]
    return point, np.percentile(bs, 2.5), np.percentile(bs, 97.5)


def write_full(acc):
    body = []
    for ti, t in enumerate(ALL):
        if ti:
            body.append(r"\midrule")
        means = {m: sum(acc[m][t]) / 4 for m, _ in ROWS}
        best = max(round(means[m], 2) for m, _ in ROWS[:3])
        for j, (m, lab) in enumerate(ROWS):
            first = LAB[t][j] if j < 2 else "        "
            mv = f"{means[m]:.2f}"
            if j < 3 and round(means[m], 2) == best:
                mv = r"\textbf{" + mv + "}"
            body.append(f"{first} & {lab} & " + " & ".join(f"{v:.2f}" for v in acc[m][t]) + f" & {mv} \\\\")
    p = L / "paper_overleaf/table_appendix/niah.tex"
    s = p.read_text()
    a = s.index("\\midrule\n") + len("\\midrule\n")
    b = s.index("% \\midrule") if "% \\midrule" in s else s.index("\\bottomrule")
    p.write_text(s[:a] + "\n".join(body) + "\n" + s[b:])


def write_cmp(acc, deltas):
    out = [GEN, r"\begin{table}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{3pt}", r"\fitcolumn{%",
           r"\begin{tabular}{lcccccccccc}", r"\toprule",
           r" & \multicolumn{2}{c}{\textbf{S-NIAH-1}} & \multicolumn{2}{c}{\textbf{S-NIAH-2}} & "
           r"\multicolumn{2}{c}{\textbf{S-NIAH-3}} & \multicolumn{4}{c}{\textbf{Mean}} \\",
           r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-11}",
           r"\textbf{Model} & orig. & rep. & orig. & rep. & orig. & rep. & orig. & rep. & $\Delta$ & 95\% CI \\",
           r"\midrule"]
    for i, (m, lab) in enumerate(CMP_ROWS):
        if i == 3:
            out.append(r"\midrule")
        cells = []
        for t in TASKS:
            cells += [sum(acc[m][t]) / 4, sum(acc[m][t + "r"]) / 4]
        o, r = np.mean(cells[0::2]), np.mean(cells[1::2])
        d, lo, hi = deltas[m]
        out.append(f"{lab} & " + " & ".join(f"{v:.2f}" for v in cells) + f" & {o:.3f} & {r:.3f} & "
                   f"${100 * d:+.1f}$ & $[{100 * lo:+.1f}, {100 * hi:+.1f}]$ \\\\")
    out += [r"\bottomrule", r"\end{tabular}", "}",
            r"\caption{\hyun{S-NIAH with the original haystacks (orig.) and with repeated haystacks (rep.), "
            r"each the mean over the four lengths of Table~\ref{tab:sniah_full}. A repeated haystack is a $64$-byte "
            r"window of the task's own haystack text (the noise passage for S-NIAH-1, the essay slice for S-NIAH-2/3), "
            r"cut at word boundaries and repeated. The key, value, needle depth, and template are those of the "
            r"original item, and every repeated item is at most as long in bytes as its original. $\Delta$ is the "
            r"change of the mean in points (rep.\ minus orig.), with a paired item-bootstrap $95\%$ confidence "
            r"interval ($2{,}000$ resamples within each task and length). The S-NIAH column of "
            r"Table~\ref{tab:main_13b} averages all six tasks.}}",
            r"\label{tab:sniah_rep}", r"\end{table}", ""]
    (L / "paper_overleaf/table_appendix/sniah_rep.tex").write_text("\n".join(out))


def main():
    M = load()
    acc = {m: {t: [cell_acc(M, m, t, Ln) for Ln in LENS] for t in ALL} for m in M}
    write_full(acc)
    rng = np.random.default_rng(0)
    deltas = {m: boot_delta(M, m, rng) for m, _ in CMP_ROWS}
    write_cmp(acc, deltas)
    mean = lambda m, ts: sum(sum(acc[m][t]) / 4 for t in ts) / len(ts)
    summ = {m: {"orig3": mean(m, TASKS), "rep3": mean(m, REP), "overall6": mean(m, ALL),
                "delta": deltas.get(m)} for m in M}
    json.dump({"per_cell": acc, "overall": summ}, open(L / "reports/niah/final/sniah_summary.json", "w"), indent=1)
    for m, v in summ.items():
        d = v["delta"]
        print(f"{m:22s} orig {v['orig3']:.3f}  rep {v['rep3']:.3f}  6-task {v['overall6']:.3f}  "
              f"delta {100 * d[0]:+.1f} [{100 * d[1]:+.1f}, {100 * d[2]:+.1f}]")


if __name__ == "__main__":
    main()
