#!/usr/bin/env python3
"""Appendix tables + figure for per-benchmark patch statistics of the five main-table models.

Reads reports/patch_stats/hist_<model>.json (written by measure_{trio,blt,hnet}.py) and writes
  paper_overleaf/table_appendix/patch_stats.tex       mean +- std patch length per benchmark
  paper_overleaf/table_appendix/patch_dist.tex        distribution summary per evaluation family
  paper_overleaf/figure_appendix/patch_len_hist.pdf   patch-length distributions (small multiples)
  reports/patch_stats/summary.md                      the same numbers, for the repo

Because patches tile the text, the mean patch length (bytes / patches, pooled over all patches
of a benchmark) IS the compression ratio (bytes per global-model position); it is reported once.
Families that pool several benchmarks pool their histograms (byte-weighted).

  python scripts/probes/patch_stats/make_tables.py
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path("/mnt/ssd2/hyun2/AUNet")
IN = ROOT / "reports/patch_stats"
OVL = ROOT / "paper_overleaf"
MODELS = ("llama", "aunet", "bpebyte", "blt", "hnet")
NAME = {"llama": "Transformer", "aunet": "AUNet", "bpebyte": "BPEByte",
        "blt": r"BLT$^{\dagger}$", "hnet": r"H-Net$^{\ddagger}$"}
PLAIN = {"llama": "Transformer", "aunet": "AUNet", "bpebyte": "BPEByte (ours)", "blt": "BLT", "hnet": "H-Net"}
ROB5 = ("hellaswag", "arc_easy", "arc_challenge", "piqa", "boolq")

# (block title, [(row label, [hist keys pooled into this row])])
ROWS = [
    ("Held-out pretraining text (BPB, latency)", [("DCLM windows", ["dclm/dclm"])]),
    ("Downstream (0-shot prompt + gold answer)", [
        ("HellaSwag", ["downstream/hellaswag"]), ("ARC-Easy", ["downstream/arc_easy"]),
        ("ARC-Challenge", ["downstream/arc_challenge"]), ("PIQA", ["downstream/piqa"]),
        ("WinoGrande", ["downstream/winogrande"]), ("BoolQ", ["downstream/boolq"]),
        ("MMLU", ["downstream/mmlu_text"])]),
    ("Retrieval (S-NIAH, 0.5k--4k bytes)", [
        ("S-NIAH-1", ["sniah/sniah1"]), ("S-NIAH-2", ["sniah/sniah2"]), ("S-NIAH-3", ["sniah/sniah3"])]),
    ("Robustness (five-task suite)", [
        ("Clean", [f"downstream/{t}" for t in ROB5]),
        ("Noise", [f"noise/{t}" for t in ROB5]),
        ("Typo", [f"typo/{t}" for t in ROB5]),
        ("Despace", [f"despace/{t}" for t in ROB5])]),
]
FAMILIES = [("DCLM", ["dclm/dclm"]),
            ("Downstream", [k for _, ks in ROWS[1][1] for k in ks]),
            ("S-NIAH", [k for _, ks in ROWS[2][1] for k in ks]),
            ("Noise", [f"noise/{t}" for t in ROB5]),
            ("Typo", [f"typo/{t}" for t in ROB5]),
            ("Despace", [f"despace/{t}" for t in ROB5])]


BLT_HIST = "hist_blt.json"     # --blt_hist: e.g. hist_blt_t16094.json for the calibrated threshold


def load():
    H = {}
    for m in MODELS:
        p = IN / (BLT_HIST if m == "blt" else f"hist_{m}.json")
        if p.exists():
            H[m] = json.load(open(p))["benches"]
    return H


def pooled(bench, keys):
    """-> (lengths array, counts array) pooled over keys."""
    c = {}
    for k in keys:
        for L, n in bench[k]["hist"].items():
            c[int(L)] = c.get(int(L), 0) + n
    Ls = np.array(sorted(c)); ns = np.array([c[L] for L in Ls])
    return Ls, ns


def stats(Ls, ns):
    N, B = ns.sum(), (Ls * ns).sum()
    mean = B / N
    std = np.sqrt((ns * (Ls - mean) ** 2).sum() / N)
    cdf = np.cumsum(ns) / N
    q = lambda p: int(Ls[np.searchsorted(cdf, p)])
    return {"mean": mean, "std": std, "median": q(0.5), "p90": q(0.9), "p99": q(0.99),
            "max": int(Ls.max()), "len1": ns[Ls == 1].sum() / N, "long_bytes": (Ls * ns)[Ls > 16].sum() / B,
            "n_patches": int(N), "bytes": int(B)}


def table_means(H):
    ms = [m for m in MODELS if m in H]
    out = [r"% GENERATED by AUNet/scripts/probes/patch_stats/make_tables.py — edit the script, not this file.",
           r"\begin{table*}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{5pt}",
           r"\begin{tabular}{l" + "c" * len(ms) + "}", r"\toprule",
           r"\textbf{Benchmark} & " + " & ".join(r"\textbf{" + NAME[m] + "}" for m in ms) + r" \\"]
    for title, rows in ROWS:
        out += [r"\midrule", r"\multicolumn{" + str(len(ms) + 1) + r"}{l}{\emph{" + title + r"}} \\"]
        for label, keys in rows:
            cells = []
            for m in ms:
                s = stats(*pooled(H[m], keys))
                cells.append(f"{s['mean']:.2f} {{\\scriptsize$\\pm${s['std']:.2f}}}")
            out.append(r"\quad " + label + " & " + " & ".join(cells) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}",
            r"\caption{Mean patch length in bytes ($\pm$ standard deviation over patches) on the exact byte "
            r"sequences each evaluation scores (context followed by the gold answer; BOS excluded). Because "
            r"patches tile the input, the mean patch length equals the compression ratio, i.e.\ the number of "
            r"input bytes per position of the global model; for the subword Transformer the unit is a Llama-3 "
            r"token. Patches come from each model's own parser: Llama-3 BPE tokens, AUNet's whitespace/word "
            r"regex, BPEByte's OnlineBPE, BLT's entropy patcher at its released threshold ($1.335$), and "
            r"H-Net's learned router (1-stage XL). Robustness rows pool the five tasks of "
            r"Table~\ref{tab:main_13b} (Noise: $15$ variants and Typo: $8$ variants, first $400$ items each; "
            r"Despace: all spaces removed, up to $2{,}000$ items; Clean: the unperturbed items). "
            r"$^{\dagger}$BLT and $^{\ddagger}$H-Net are external references.}",
            r"\label{tab:patch_stats}", r"\end{table*}", ""]
    return "\n".join(out)


def table_dist(H):
    ms = [m for m in MODELS if m in H]
    out = [r"% GENERATED by AUNet/scripts/probes/patch_stats/make_tables.py — edit the script, not this file.",
           r"\begin{table*}[t]", r"\centering", r"\small", r"\setlength{\tabcolsep}{5pt}",
           r"\begin{tabular}{llrrrrrr}", r"\toprule",
           r"\textbf{Evaluation} & \textbf{Model} & \textbf{Median} & \textbf{P90} & \textbf{P99} & "
           r"\textbf{Max} & \textbf{1-byte (\%)} & \textbf{Bytes in $>$16\,B (\%)} \\"]
    for fi, (fam, keys) in enumerate(FAMILIES):
        out.append(r"\midrule")
        for j, m in enumerate(ms):
            s = stats(*pooled(H[m], keys))
            lead = fam if j == 0 else ""
            out.append(f"{lead} & {NAME[m]} & {s['median']} & {s['p90']} & {s['p99']} & {s['max']} & "
                       f"{100 * s['len1']:.1f} & {100 * s['long_bytes']:.1f} \\\\")
    out += [r"\bottomrule", r"\end{tabular}",
            r"\caption{Patch-length distribution (bytes) per evaluation family, pooled over the benchmarks of "
            r"Table~\ref{tab:patch_stats}. P90/P99 are percentiles over patches; \emph{1-byte} is the share of "
            r"patches that hold a single byte (no compression at that position), and \emph{Bytes in $>$16\,B} is "
            r"the share of input bytes that land in patches longer than $16$ bytes (information pooled into one "
            r"global position). Figure~\ref{fig:patch_len_hist} plots the full distributions. "
            r"$^{\dagger}$BLT and $^{\ddagger}$H-Net are external references.}",
            r"\label{tab:patch_dist}", r"\end{table*}", ""]
    return "\n".join(out)


def figure(H, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    # model colors/styles follow the radar figure (reports/parse/star_draw.py); dashed = external
    col = {"llama": "#0072B2", "aunet": "#E69F00", "bpebyte": "#009E73", "blt": "#CC79A7", "hnet": "#56B4E9"}
    ls = {"llama": "-", "aunet": "-", "bpebyte": "-", "blt": "--", "hnet": "--"}
    mk = {"llama": "o", "aunet": "s", "bpebyte": "D", "blt": "^", "hnet": "v"}
    CAP = 24                                       # lengths >= CAP fold into the last bin
    ms = [m for m in MODELS if m in H]
    fig, axes = plt.subplots(2, 3, figsize=(10.5, 5.6), sharex=True, sharey=True)
    for ax, (fam, keys) in zip(axes.flat, FAMILIES):
        for m in ms:
            Ls, ns = pooled(H[m], keys)
            y = np.zeros(CAP)
            for L, n in zip(Ls, ns):
                y[min(L, CAP) - 1] += n
            y = y / ns.sum()
            x = np.arange(1, CAP + 1)
            keep = y > 0
            ax.plot(x[keep], y[keep], ls[m], color=col[m], lw=1.6, marker=mk[m], ms=3.2,
                    label=PLAIN[m], zorder=3 if m == "bpebyte" else 2)
        ax.set_title(fam, fontsize=11)
        ax.set_yscale("log")
        ax.set_ylim(1e-5, 1.2)
        ax.set_xticks([1, 4, 8, 12, 16, 20, CAP])
        ax.set_xticklabels(["1", "4", "8", "12", "16", "20", f"{CAP}+"])
        ax.grid(color="#e1e0d9", lw=0.6)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
    for ax in axes[1]:
        ax.set_xlabel("Patch length (bytes)")
    for ax in axes[:, 0]:
        ax.set_ylabel("Share of patches")
    h, l = axes[0, 0].get_legend_handles_labels()
    fig.legend(h, l, loc="upper center", ncol=len(ms), frameon=False, fontsize=10, bbox_to_anchor=(0.5, 1.02))
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(IN / "patch_len_hist.png", dpi=150, bbox_inches="tight")
    return path


def summary_md(H):
    ms = [m for m in MODELS if m in H]
    lines = ["# Patch statistics per benchmark (five main-table models)", "",
             "Generated by `scripts/probes/patch_stats/make_tables.py` from `hist_<model>.json`.",
             "Mean patch length = compression ratio (bytes per global position); std over patches.", "",
             "| row | " + " | ".join(PLAIN[m] for m in ms) + " |", "|---" * (len(ms) + 1) + "|"]
    for title, rows in ROWS:
        for label, keys in rows:
            cells = []
            for m in ms:
                s = stats(*pooled(H[m], keys))
                cells.append(f"{s['mean']:.2f} ± {s['std']:.2f}")
            lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines += ["", "| family | model | median | p90 | p99 | max | 1-byte % | bytes in >16B % |", "|---" * 8 + "|"]
    for fam, keys in FAMILIES:
        for m in ms:
            s = stats(*pooled(H[m], keys))
            lines.append(f"| {fam} | {PLAIN[m]} | {s['median']} | {s['p90']} | {s['p99']} | {s['max']} | "
                         f"{100 * s['len1']:.1f} | {100 * s['long_bytes']:.1f} |")
    (IN / "summary.md").write_text("\n".join(lines) + "\n")


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--blt_hist", default="hist_blt.json")
    ap.add_argument("--out_dir", default=None, help="write tables/figure here instead of paper_overleaf")
    a = ap.parse_args()
    global BLT_HIST
    BLT_HIST = a.blt_hist
    H = load()
    missing = [m for m in MODELS if m not in H]
    if missing:
        print("WARNING: no histogram yet for", missing)
    od = Path(a.out_dir) if a.out_dir else None
    if od:
        od.mkdir(parents=True, exist_ok=True)
    (od / "patch_stats.tex" if od else OVL / "table_appendix/patch_stats.tex").write_text(table_means(H))
    (od / "patch_dist.tex" if od else OVL / "table_appendix/patch_dist.tex").write_text(table_dist(H))
    figure(H, od / "patch_len_hist.pdf" if od else OVL / "figure_appendix/patch_len_hist.pdf")
    summary_md(H)
    print((IN / "summary.md").read_text())


if __name__ == "__main__":
    main()
