#!/usr/bin/env python3
"""How often is a BPEByte OnlineBPE patch an actual Llama-3 vocabulary entry? (CPU)

OnlineBPE (greedy/root) commits the longest traversable trie path at a dead-end and never backtracks
to the longest complete vocab item inside it (paper Sec. 4, after Eq. bpe_root_boundary), so a patch
is either a vocab entry or a proper prefix of one. This measures the split on the same byte strings
as tab:patch_stats (reports/patch_stats/texts.jsonl: ctx + gold answer, BOS excluded) with the same
tiling convention (patch k = [start_k, start_{k+1}), i.e. the shared dead-end byte excluded).

  cd lingua && .venv/bin/python ../scripts/probes/patch_stats/measure_invocab.py \
      [--tex ../paper_overleaf/table_appendix/invocab.tex]
"""
import argparse, base64, json, sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))                                # scripts/probes
from patch_common import ROOT, check_gate, lengths_from_starts, load_texts, Hist  # noqa: E402
sys.path.append(str(ROOT / "scripts/probes"))                       # compression_stability (untracked)
from compression_stability import build_parser, TOK  # noqa: E402

OUT = HERE.parents[2] / "reports/patch_stats/invocab_bpebyte.json"
ROB = ("hellaswag", "arc_easy", "arc_challenge", "piqa", "boolq")     # robustness five-task suite
AVG5 = ("hellaswag", "arc_easy", "arc_challenge", "piqa", "winogrande")  # main-table downstream Avg5
NAMES = {"hellaswag": "HellaSwag", "arc_easy": "ARC-Easy", "arc_challenge": "ARC-Challenge",
         "piqa": "PIQA", "boolq": "BoolQ", "winogrande": "WinoGrande",
         "sniah1": "S-NIAH-1", "sniah2": "S-NIAH-2", "sniah3": "S-NIAH-3"}


def measure():
    vocab = {base64.b64decode(l.split()[0]) for l in open(TOK) if l.strip()}
    prefixes = {v[:i] for v in vocab for i in range(1, len(v))}
    parse, gate = build_parser("bpebyte"), Hist()
    st = defaultdict(lambda: {"n_items": 0, "n_patches": 0, "n_in": 0, "bytes": 0, "bytes_in": 0,
                              "n_not_prefix": 0, "oov": Counter()})
    for r in load_texts():
        if r["bench"] == "mmlu_text":                                # not in tab:main_13b
            continue
        bs = r["text"].encode("utf-8")
        lens = lengths_from_starts(parse(r["text"]), len(bs))
        if r["group"] == "dclm":
            gate.add(r, lens)
        d = st[f"{r['group']}/{r['bench']}"]
        d["n_items"] += 1
        s = 0
        for L in lens:
            p = bs[s:s + L]
            s += L
            d["n_patches"] += 1
            d["bytes"] += L
            if p in vocab:
                d["n_in"] += 1
                d["bytes_in"] += L
            else:
                d["oov"][p] += 1
                d["n_not_prefix"] += p not in prefixes
    if not check_gate("bpebyte", gate):
        raise SystemExit("gate failed — parser does not reproduce the paper-time measurement")
    out = {k: {**{x: v[x] for x in v if x != "oov"},
               "top_oov": [[p.decode("utf-8", "replace"), c] for p, c in v["oov"].most_common(20)]}
           for k, v in sorted(st.items())}
    OUT.write_text(json.dumps({"parser": "bpebyte (OnlineBPE greedy/root, Llama-3 trie)",
                               "tokenizer": str(TOK), "benches": out}, indent=1, ensure_ascii=False))
    print("wrote", OUT)
    return out


def rate(d, keys):
    keys = [k for k in keys if k in d]
    return 100 * sum(d[k]["n_in"] for k in keys) / sum(d[k]["n_patches"] for k in keys)


def table(d):
    f = lambda keys: f"{rate(d, keys):.2f}"
    row = lambda name, cells: "\\quad " + name + " & " + " & ".join(cells) + " \\\\"
    na = "--"
    L = ["% GENERATED by AUNet/scripts/probes/patch_stats/measure_invocab.py — edit the script, not this file.",
         "\\begin{table}[t]", "\\centering", "\\small", "\\setlength{\\tabcolsep}{4pt}",
         "\\begin{tabular}{lcccc}", "\\toprule",
         "\\textbf{Benchmark} & \\textbf{Clean} & \\textbf{Noise} & \\textbf{Typo} & \\textbf{Despace} \\\\",
         "\\midrule",
         "\\multicolumn{5}{l}{\\emph{Held-out pretraining text}} \\\\",
         row("DCLM windows", [f(["dclm/dclm"]), na, na, na]),
         "\\midrule",
         "\\multicolumn{5}{l}{\\emph{Downstream and robustness}} \\\\"]
    for t in ROB:
        L.append(row(NAMES[t], [f([f"{g}/{t}"]) for g in ("downstream", "noise", "typo", "despace")]))
    L.append(row(NAMES["winogrande"], [f(["downstream/winogrande"]), na, na, na]))
    L.append("\\midrule")
    L.append(row("Downstream Avg5 (pooled)", [f([f"downstream/{t}" for t in AVG5]), na, na, na]))
    L.append(row("Five-task suite (pooled)", [f([f"{g}/{t}" for t in ROB])
                                              for g in ("downstream", "noise", "typo", "despace")]))
    L += ["\\midrule", "\\multicolumn{5}{l}{\\emph{Retrieval (S-NIAH, 0.5k--4k bytes)}} \\\\"]
    for t in ("sniah1", "sniah2", "sniah3"):
        L.append(row(NAMES[t], [f([f"sniah/{t}"]), na, na, na]))
    L += ["\\bottomrule", "\\end{tabular}",
          "\\caption{\\hyun{Share of BPEByte's OnlineBPE patches (\\%) that are complete entries of the "
          "Llama-3 vocabulary $\\mathcal{R}$, on the byte sequences of Table~\\ref{tab:patch_stats} "
          "(context followed by the gold answer, BOS excluded; patches tile the input, so the dead-end "
          "byte shared with the next patch is excluded). Every remaining patch is a proper prefix of an "
          "entry of $\\mathcal{R}$. Rows and item subsets follow Table~\\ref{tab:patch_stats}: Downstream "
          "Avg5 pools the five tasks of the downstream average in Table~\\ref{tab:main_13b}, and the "
          "five-task suite pools those of its robustness columns.}}",
          "\\label{tab:invocab}", "\\end{table}"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", help="write the appendix table here")
    ap.add_argument("--from_json", action="store_true", help="reuse reports/patch_stats/invocab_bpebyte.json")
    a = ap.parse_args()
    d = json.loads(OUT.read_text())["benches"] if a.from_json else measure()
    for k, v in d.items():
        print(f"{k:26s} items={v['n_items']:5d} B/patch={v['bytes'] / v['n_patches']:.3f} "
              f"in-vocab={100 * v['n_in'] / v['n_patches']:.2f}% (bytes {100 * v['bytes_in'] / v['bytes']:.2f}%) "
              f"not-a-prefix={v['n_not_prefix']}")
    if a.tex:
        Path(a.tex).write_text(table(d))
        print("wrote", a.tex)


if __name__ == "__main__":
    main()
