"""Combined before_root:bt rollback animation -> one GIF/MP4.

Two REAL captured traces, back to back with title cards:
  Case 1: prompt 'hello' (complete word) + ' world'   -> rb=1
          ('hello|' boundary held speculative, commits late -> drop '·worl', re-sample)
  Case 2: prompt 'hello wor' (ends MID-TOKEN) + 'ld'   -> rb=1
          (1st generated byte commits the prompt's 'hello|'; rollback drops ONLY the
           generated byte -- prompt bytes are never rolled back, keep = prompt length)

Run (training venv, CPU):
  cd ../lingua && CUDA_VISIBLE_DEVICES="" .venv/bin/python ../viz/bt_rollback_combined.py
"""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, FancyBboxPatch
from matplotlib.animation import FuncAnimation, PillowWriter

GRAY, BLUE, RED, INK, PUR = "#9AA0A6", "#1A73E8", "#D93025", "#202124", "#9334E6"
CW, CH, Y = 1.0, 1.2, 0.0

# each frame: dict(case, plen, s, bars, drop, partial, cap)  OR  dict(title=...)
def F(case, plen, s, bars, drop, partial, cap):
    return dict(case=case, plen=plen, s=s, bars=bars, drop=drop, partial=partial, cap=cap)

CASE1 = [
    F(1, 5, "hello",       [],      [],            None, "prompt 'hello' fed - tail boundary held speculative (commit_margin=2)"),
    F(1, 5, "hello ",      [],      [],            None, "feed '·'  ->  ACCEPT"),
    F(1, 5, "hello w",     [],      [],            None, "feed 'w'  ->  ACCEPT"),
    F(1, 5, "hello wo",    [],      [],            None, "feed 'o'  ->  ACCEPT"),
    F(1, 5, "hello wor",   [],      [],            None, "feed 'r'  ->  ACCEPT   (no boundary committed yet)"),
    F(1, 5, "hello worl",  [4],     [5,6,7,8,9],   None, "feed 'l': 'hello|' commits (change before frontier) -> '·worl' off-policy"),
    F(1, 5, "hello",       [4],     [],            None, "ROLLBACK (rb=1): drop '·worl', restore parser, re-sample from 'hello|'"),
    F(1, 5, "hello ",      [4],     [],            None, "feed '·'  ->  ACCEPT"),
    F(1, 5, "hello w",     [4],     [],            None, "feed 'w'  ->  ACCEPT"),
    F(1, 5, "hello wo",    [4],     [],            None, "feed 'o'  ->  ACCEPT"),
    F(1, 5, "hello wor",   [4],     [],            None, "feed 'r'  ->  ACCEPT"),
    F(1, 5, "hello worl",  [4],     [],            None, "feed 'l'  ->  ACCEPT   (stable now)"),
    F(1, 5, "hello world", [4],     [],            None, "feed 'd'  ->  ACCEPT"),
    F(1, 5, "hello world", [4,10],  [],            None, "finalize(): hello|·world|  ==  offline get_levels_mask  OK"),
]
CASE2 = [
    F(2, 9, "hello wor",   [],      [],   (5, 8),  "prompt ends MID-TOKEN: '·wor' incomplete - boundaries speculative"),
    F(2, 9, "hello worl",  [4],     [9],  (5, 9),  "feed 'l' (1st gen byte): 'hello|' commits @tok5 -> 'l' off-policy"),
    F(2, 9, "hello wor",   [4],     [],   (5, 8),  "ROLLBACK (rb=1): drop ONLY 'l' - prompt bytes never dropped (keep = prompt len)"),
    F(2, 9, "hello worl",  [4],     [],   (5, 9),  "re-sample 'l'  ->  ACCEPT"),
    F(2, 9, "hello world", [4],     [],   (5, 10), "feed 'd'  ->  ACCEPT - '·world' completes the partial token"),
    F(2, 9, "hello world", [4,10],  [],   None,    "finalize(): hello|·world|  ==  offline  OK"),
]
T1 = dict(title="Case 1 / 2\nprompt = 'hello'  (complete word)\ngenerate ' world'")
T2 = dict(title="Case 2 / 2\nprompt = 'hello wor'  (ends MID-TOKEN)\ngenerate 'ld'   ->   same 'hello world'")

FRAMES = [T1] + CASE1 + [T2] + CASE2

fig, ax = plt.subplots(figsize=(13, 4.0))
fig.patch.set_facecolor("white")


def rollbacks_so_far(idx):
    f = FRAMES[idx]
    if "title" in f:
        return 0
    n = 0
    for j in range(idx + 1):
        g = FRAMES[j]
        if "title" not in g and g["case"] == f["case"] and g["cap"].startswith("ROLLBACK"):
            n += 1
    return n


def draw(idx):
    ax.clear(); ax.set_xlim(-0.6, 13.6); ax.set_ylim(-2.7, 2.4); ax.axis("off")
    f = FRAMES[idx]
    if "title" in f:
        ax.text(6.5, 0.4, f["title"], ha="center", va="center", fontsize=18,
                family="monospace", color=INK, linespacing=1.8, fontweight="bold")
        ax.text(6.5, 2.1, "before_root:bt online generation", ha="center",
                fontsize=12, family="monospace", color=GRAY)
        return
    plen, s, bars, drop, partial, cap = f["plen"], f["s"], f["bars"], f["drop"], f["partial"], f["cap"]
    ax.text(-0.4, 2.05, f"Case {f['case']}: " +
            ("'hello' + ' world'" if f['case'] == 1 else "'hello wor' + 'ld'"),
            fontsize=13, fontweight="bold", family="monospace")
    ax.text(13.5, 2.05, f"rollbacks: {rollbacks_so_far(idx)}", fontsize=11, ha="right",
            color=RED, family="monospace")
    for k, ch in enumerate(s):
        is_gen = k >= plen
        if k in drop:    fc, ec, tc = "#fde7e6", RED, RED
        elif is_gen:     fc, ec, tc = "#e8f0fe", BLUE, BLUE
        else:            fc, ec, tc = "#f1f3f4", GRAY, INK
        x = k * CW
        ax.add_patch(FancyBboxPatch((x + 0.06, Y + 0.06), CW - 0.12, CH - 0.12,
                     boxstyle="round,pad=0.02,rounding_size=0.08",
                     linewidth=2, edgecolor=ec, facecolor=fc))
        ax.text(x + CW / 2, Y + CH / 2, "·" if ch == " " else ch, ha="center", va="center",
                fontsize=20, family="monospace", color=tc, fontweight="bold" if is_gen else "normal")
    for b in bars:
        x = (b + 1) * CW
        ax.plot([x, x], [Y - 0.12, Y + CH + 0.12], color=RED, linewidth=5, solid_capstyle="round")
        ax.text(x, Y + CH + 0.28, "patch end", ha="center", fontsize=8, color=RED)
    if partial:
        a, b = partial
        x0, x1 = a * CW + 0.1, (b + 1) * CW - 0.1
        ax.plot([x0, x1], [Y - 0.32, Y - 0.32], color=PUR, lw=2.2, ls=(0, (4, 3)))
        ax.text((x0 + x1) / 2, Y - 0.62, "partial token -> completed during generation",
                ha="center", fontsize=8.5, color=PUR, style="italic")
    sx = plen * CW
    ax.annotate("prompt | generated", xy=(sx, Y + CH + 0.05), xytext=(sx, Y + CH + 0.78),
                ha="center", fontsize=8, color=INK, arrowprops=dict(arrowstyle="-", color=INK, lw=1))
    for j, (txt, fcc, ec) in enumerate([("prompt", "#f1f3f4", GRAY), ("generated", "#e8f0fe", BLUE),
                                        ("rolled back", "#fde7e6", RED)]):
        lx = 0.2 + j * 2.4
        ax.add_patch(Rectangle((lx, -1.55), 0.3, 0.3, facecolor=fcc, edgecolor=ec))
        ax.text(lx + 0.4, -1.4, txt, fontsize=9, va="center", color=ec if txt != "prompt" else INK)
    ax.plot([7.5, 7.5], [-1.57, -1.25], color=RED, lw=5, solid_capstyle="round")
    ax.text(7.7, -1.4, "patch boundary", fontsize=9, va="center", color=RED)
    is_roll = cap.startswith("ROLLBACK") or "off-policy" in cap
    ax.text(-0.4, -2.3, cap, fontsize=11, family="monospace",
            color=RED if is_roll else INK, fontweight="bold" if is_roll else "normal")


# playback order: hold title cards, rollbacks, and finalize frames longer
order = []
for i, f in enumerate(FRAMES):
    order.append(i)
    if "title" in f:
        order += [i, i, i]
    elif f["cap"].startswith(("ROLLBACK", "finalize")) or "off-policy" in f["cap"]:
        order += [i, i]

anim = FuncAnimation(fig, lambda k: draw(order[k]), frames=len(order), interval=820, blit=False)
GIF = "/NHNHOME/WORKSPACE/0226010285_F/MINDlab/hyunw3/AUNet/viz/bt_rollback_combined.gif"
anim.save(GIF, writer=PillowWriter(fps=1.3))
print("wrote", GIF)
try:
    anim.save(GIF.replace(".gif", ".mp4"), writer="ffmpeg", fps=1.3, dpi=120)
    print("wrote", GIF.replace(".gif", ".mp4"))
except Exception as e:
    print("mp4 skipped:", e)
